### PR TITLE
EWL-6805: Align Article Stub Title and Image

### PR DESCRIPTION
**Pull request by adriansmuresan**
**Jira Ticket**
- [EWL-6805: Align Article Stub Title and Image](https://issues.ama-assn.org/browse/EWL-6805)

## Description
Revise CSS in order to align the title and image on the article stub(right side column) at mobile and desktop viewports as presented in the zeplin(check ticket).

## To Test
- [ ] run `gulp serve`
- [ ] enable local SG2 testing in your D8 env, clear cache `drush @one.local cr`
- [ ] Navigate to (http://ama-one.local/residents-students/specialty-profiles/residents-share-4-tips-assessing-specialty-lifestyle) and check that the title and image in the article stub are aligned to the left. For example, this screenshot, from the URL above: screen shot 2019-02-26 at 11 53 17 am
- [ ] Did you test in IE 11?

## Visual Regressions

A report is available [here](http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/feature/EWL-6805-align-article-stub-title-and-image/html_report/index.html).

### Desktop
image

### Mobile
image

### BEFORE
screen shot 2019-02-19 at 12 54 33 pm
### AFTER
screen shot 2019-02-26 at 11 52 41 am

### BEFORE
screen shot 2019-02-26 at 11 52 52 am
### AFTER
screen shot 2019-02-26 at 11 53 17 am

## Remaining Tasks
N/A

## Additional Notes
N/A

---

### CODE REVIEW

**Comment by russom-woldezghi** [comment]
@JaeBea Are you reviewing this PR? 

Also, @adriansmuresan it looks like Travis is failing on this PR. Can you take a look?

**Comment by adriansmuresan** [comment]
@russom-woldezghi  how can I trigger Travis to run again. It says it timed out.

**Comment by russom-woldezghi** [comment]
@adriansmuresan - You should be able to click on "X" icon and it will take you to Travis. You should be able to see "Restart build". I have restarted the build here: https://travis-ci.org/AmericanMedicalAssociation/ama-style-guide-2/builds/485526180

**Comment by JaeBea** [comment]
Awaiting confirmation on whether this work needs to update sidebar articles to align with updated ux designs.

**Comment by JaeBea** [comment]
@adriansmuresan Please see updated ticket.

**Comment by russom-woldezghi** [comment]
I am still seeing the image and the title not aligned for article stubs (at the bottom of the page) on mobile, see below: 

screen shot 2019-02-19 at 12 54 33 pm

**Comment by russom-woldezghi** [comment]
I have also updated this PR to also address the four-up article stubs margins, below main content, before the footer. See screenshots: 

## Four up list of article stub, below content, before the footer. 
### BEFORE
screen shot 2019-02-19 at 12 54 33 pm
### AFTER
screen shot 2019-02-26 at 11 52 41 am

## Right sidebar column, article stub list
### BEFORE
screen shot 2019-02-26 at 11 52 52 am
### AFTER
screen shot 2019-02-26 at 11 53 17 am

**Review by JaeBea — APPROVED** [review]
@russom-woldezghi ,
This looks good to go. I will approve and merge into develop.

**Pull request merged**
