### PR TITLE
do drupal deploy during release

### PR DESCRIPTION
**Pull request by labbydev**
## Ticket(s)
N/A

## Description
Update `gulp release` to also include the `drupal-deploy` command so that `dev-assets` also gets updated. 

## To Test
- [ ] `gulp release`
- [ ] Observe that code has been updated on the `dev-assets` branch

## Visual Regressions
N/A

## Relevant Screenshots/GIFs
N/A

## Remaining Tasks
N/A

## Additional Notes
N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Review by Brian-Clement — COMMENTED** [review]
@labbydev this looks right, but I'm going to hold off on actually testing it until we are done with today's deploys.

**Comment by labbydev** [comment]
@Brian-Clement can you take another look at this?

**Comment by Brian-Clement** [comment]
@labbydev will do.

**Review by Brian-Clement — APPROVED** [review]

**Comment by Brian-Clement** [comment]
@labbydev this failed for me in `develop` as well, so I reverted it.  If this is too much effort, we can just run the `gulp drupal-deploy` and `gulp release` tasks separately until the Travis deployments are sorted.

**Pull request merged**
