### PR TITLE
EWL-4600 search filter

### PR DESCRIPTION
**Pull request by designerneil**
Adds search filter to the event listing filters## Ticket(s)

**Jira Ticket**
- [EWL-4600: SG2 | Create Page Search Atom](https://issues.ama-assn.org/browse/EWL-5124)

## Description
On mobile devices the content is too close to the edge of the screen per UX feedback

## To Test
- [ ] `gulp serve`
- [ ] visit http://localhost:3000/?p=pages-event-listing
- [ ] click on the location accordion header
- [ ] observe the a search filter is present above the checkmarks
- [ ] search for a state
- [ ] observe the states get filtered depending on what is being search for after 3 characters are entered

## Visual Regressions

ran `backstop test`
the only failures were padding and shifting issues that backstop sometimes shows.

## Relevant Screenshots/GIFs
screen shot 2018-05-29 at 11 20 22 am

## Remaining Tasks
N/A

## Additional Notes
N/A
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by labbydev** [comment]
@designerneil this all looks good, but I'm seeing what I think are the mobile buttons on desktop. Does [this](https://www.useloom.com/share/cbe957adad9a4809bd34dfa7e8c45102) look correct to you?

**Comment by designerneil** [comment]
@labbydev are you sure your viewport size is desktop? The buttons showing right from the get go tells me your screensize is smaller than 1069px.

**Comment by labbydev** [comment]
@designerneil if the buttons are showing due to an issue with the viewport size then the page isn't getting the tablet layout early enough. Since that sidebar shouldn't exist at tablet.

**Comment by designerneil** [comment]
@labbydev removed buttons for desktop viewport sizes. Thanks

**Review by labbydev — APPROVED** [review]

**Comment by labbydev** [comment]
@designerneil everything is good to go but now I'm getting some conflicts with the backstop images.

**Pull request merged**
