### PR TITLE
EWL-5077 - Add engine scripts to backstop 

### PR DESCRIPTION
**Pull request by designerneil**
## Ticket(s)

**Jira Ticket**
- [EWL-5077: SG2 | Add backstop depedency engine_scripts](https://issues.ama-assn.org/browse/EWL-5077)

## Description
Backstop is currently broken. It chokes on on the pages section because it has to find all the selectors noted in the test. These selectors are already tested in organisms and molecules. 

Engine scripts folder is missing from backstop which is causing many errors during testing. These errors cause backstop to skip the onBefore and After tests.

Backtop npm module is not the latest. It should be 3.2.16

## To Test

- [ ]  `npm install`
- [ ] `gulp serve`
- [ ] `backstop test`
- [ ] get a cup of coffee
- [ ] Observe if backstop finished all the tests and opens a new browser window with 0 failures

## Visual Regressions

- Ran `backstop test`
- Noticed 40 failures. Most of the failures are from the elements shifting by a couple of pixels.
- The resource page doesn't seem to have been updated. The tags have more padding and margins on the page.
- Resource page refs have been added

screen shot 2018-05-15 at 10 19 08 am

## Relevant Screenshots/GIFs
screen shot 2018-05-15 at 10 19 32 am

## Remaining Tasks
N/A

## Additional Notes
N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by JaeBea** [comment]
@designerneil, the issues with backstop references for the Resources page has a bug ticket in JIRA. Please make sure to update.

https://issues.ama-assn.org/browse/EWL-5061

@labbydev Do you feel this can be merged even with the additional work dictated in the ticket mentioned above?

**Review by JaeBea — APPROVED** [review]
Backstop works without issue for me. I do get errors, BACKSTOP ERROR: Chromy error: WaitTimeoutError. See scenario – molecules-promo, however I had these before your PR.

**Comment by designerneil** [comment]
@JaeBea I'm comfortable with including the backstop image refs for resource page here. If that's the only additional change.

But in general you are right we should have separate tickets to capture backstop image refs not being updated in develop.

**Comment by designerneil** [comment]
@JaeBea per our conversation backstop images should be pushed into develop when a branch gets merged. In my experience when multiple branches get merged into develop backstop images seem to ignore the images and flag the changes as errors.

**Review by labbydev — APPROVED** [review]

**Pull request merged**
