### PR TITLE
Add border-top to footer Product menu 

### PR DESCRIPTION
**Pull request by Brian-Clement**
## Ticket(s)
No known JIRA ticket.

## Description
- Moved the `border-top` for the `ama__footer__menu-products` class to the base style, so it is applied on mobile as well.
- Added `margin-top` and `padding-top` to ensure consistent spacing on mobile (these didn't seem to impact tablet and desktop displays in my Backstop testing)

## To Test
- [ ] `gulp serve`
- [ ] Look at the footer.  Observe the line above the Product Menu remains in place on mobile

## Visual Regressions

_Please provide the pull request ID below. This will then reference the automated VRT report after it has been generated._

A report is available [here](http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/544/html_report/index.html).

**Before proceeding:** Run visual regression tests locally to ensure new work does not introduce new bugs.

_The visual regression tests always compare against the production version of the style guide. Changes and new work will show up as test failures. Please describe your work so that the report can be reviewed by the team._

If you are creating or updating a pattern be sure you have created or updated the [scenario in `backstop.json`](ama-style-guide-2/styleguide/backstop.json).

_After changes in the report are documented and demonstrate your desired changes, please mark the pull request as `ready for review`.

For more information on visual regression testing review the [How do I run tests?](https://issues.ama-assn.org:8446/confluence/pages/viewpage.action?pageId=23298568) document in Confluence.

## Relevant Screenshots/GIFs
image

## Remaining Tasks
N/A

## Additional Notes
N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by designerneil** [comment]
I noticed the margin around the line and menu doesn't match the content above it. Does it need to match?

_l__default_homepage___american_medical_association

**Comment by Brian-Clement** [comment]
@designerneil you are probably right that it should be matching in those other areas, but that isn't covered by the scope of this ticket.  Unless these things are regressions introduced by this code I say we defer them to a separate ticket.

**Comment by designerneil** [comment]
@Brian-Clement works as described.

**Review by designerneil — APPROVED** [review]

**Review by JaeBea — APPROVED** [review]
@Brian-Clement ,

This seems to be working as expected. As second reviewer I will approve and merge into develop.

**Pull request merged**
