### PR TITLE
SC-12: Theme Search Connector

### PR DESCRIPTION
**Pull request by russom-woldezghi**
## Ticket(s)
- [SC-12: Theme Search Connector](https://issues.ama-assn.org/browse/SC-12)

## Description
- Adds custom scss file for search connector theming
- Adds new class for two column layout, so aside element can be placed below search results.

## To Test
- [ ] Enable local styleguide
- [ ] Checkout this branch for Drupal side of work: https://github.com/AmericanMedicalAssociation/ama-d8/pull/1589
- [ ] Clear Drupal cache
- If you are working remotely, sign into the VPN, to see results. 
- [ ] Navigate to http://ama-one.local/search?search=journal
- [ ] Observe markup for each source detailed in this screenshot: 

**MOBILE/TABLET**
Screen Shot 2019-09-18 at 3 51 40 PM
(**Note** Discover more header and text are not finished in the screenshot, from Zeplin. Links to Zeplin are provided below.)

**DESKTOP**
Screen Shot 2019-09-18 at 3 52 05 PM

- [ ] On mobile/tablet, the list of results should be side by side and can scroll to view the results. 
- [ ] Test in IE 11
- [ ] Test in FF
- [ ] Test in Safari
- [ ] Test in Chrome

## Links to Zeplin
- Desktop: https://app.zeplin.io/project/59dd1f9c36a8b21d569bb9e8/screen/5d0bda0545c0e559e21bc2ea
- Tablet: https://app.zeplin.io/project/59dd1f9c36a8b21d569bb9e8/screen/5d27945dbf24167764d2566b  - (Looks a bit off in styling, should match mobile/desktop more).
- Mobile: https://app.zeplin.io/project/59dd1f9c36a8b21d569bb9e8/screen/5d24e37fbe5a7137512445c6

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Review by joshuathorne — CHANGES_REQUESTED** [review]
Reviewed along with https://github.com/AmericanMedicalAssociation/ama-d8/pull/1589.

New components need to be included as styleguide patterns with corresponding twig and json files. If you'd like to do this in another ticket I can approve this one, or you can amend this PR, totally up to you.

Aside from that, looks good.

**Comment by russom-woldezghi** [comment]
@Dr-Zee I have added the search connector component as a molecule and updated the two-column-left page to support mobile treatment for search connector block.

**Comment by russom-woldezghi** [comment]
@Dr-Zee I have added the search connector component as a molecule and updated the two-column-left page to support mobile treatment for search connector block.

**Review by joshuathorne — APPROVED** [review]
Looks great.

**Pull request merged**
