### PR TITLE
EWL-4605 & EWL-4606 Event Stub and Event Stub as Featured

### PR DESCRIPTION
**Pull request by labbydev**
## Ticket(s)
**Do not** submit a Pull Request without a relevant JIRA ticket or Github issue! If you are creating a new pattern or feature, create an issue describing the need for this feature in Github **first** and then link to it below.

**Github Issue**
- [Issue 4605: Create Even Stub Molecule](https://github.com/AmericanMedicalAssociation/AMA-style-guide/issues/4605)
- [Issue 4606: Create Event Stub as Featured variant](https://github.com/AmericanMedicalAssociation/AMA-style-guide/issues/4606)

## Description
Create a molecule for the event stub as it appears on the event listing and create a variant for the ~"as Featured"~ "as Sticky" version.

### Event Stub Molecule
- [x] `git checkout feature/EWL-4605-event-stubs`
- [x] `gulp serve`
- [x] Navigate to SG2
- [x] Click "Molecules"
- [x] Observe you see "Event Stub"
- [x] Click "Event Stub"
- [x] Observe you see a h2 with the event name, linked 
- [x] Observe you see a h3 with the event detail
- [x] Observe you see the event date
- [x] Observe you see a summary or excerpt
- [x] Observe you see an image
- [x] Observe you see a "Discount for AMA Members"
- [x] Observe you see a CME badge icon
- [x] Observe you see a horizontal rule on the bottom
---
### Event Stub as Featured variant
- [x] `git checkout feature/EWL-4605-event-stubs`
- [x] `gulp serve`
- [x] Navigate to SG2
- [x] Click "Molecules"
- [x] Observe you see "Event Stub as ~Featured~ Sticky"
- [x] Click "Event Stub as ~Featured~ Sticky"
- [x] Observe you see an "Event Stub"
- [x] Observe that "Event Stub" has a light gray background
---
### Event List Organism
- [x] `git checkout feature/EWL-4605-event-stubs`
- [x] `gulp serve`
- [x] Navigate to SG2
- [x] Click "Organisms"
- [x] Observe you see "Event List"
- [x] Click "Event List"
- [x] Observe you see a listing "Event Stub" molecules
- [x] Observe that the first "Event Stub" has a light gray background
---
### Event Listing Page
- [x] `git checkout feature/EWL-4605-event-stubs`
- [x] `gulp serve`
- [x] Navigate to SG2
- [x] Click "Pages"
- [x] Observe you see "Event List" in the `pageContent` region of the page

## Visual Regressions
I have updated the `backstop.json` and the screenshots. However, I continue to get a number of Chromy errors when running backstop that means that there are some items that aren't being tested at all. 

## Relevant Screenshots/GIFs
screen shot 2018-05-18 at 10 24 32 am
screen shot 2018-05-18 at 10 24 41 am

## Remaining Tasks
N/A

## Additional Notes
N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by labbydev** [comment]
Adding a `priority` flag for this since @nstriedinger is going to branch off of this for the work on EWL-4607

**Comment by csj1012** [comment]
Hi @labbydev - the first two scenarios look good. However, I am not seeing "Event List" in the Organisms list, and the display in the "Event Listing" page pattern looks off. (Basically, all the unchecked steps in the "To Test" section might need a second look):

screen shot 2018-05-18 at 1 30 34 pm
screen shot 2018-05-18 at 1 31 28 pm

**Review by csj1012 — CHANGES_REQUESTED** [review]
See my comment above.

**Review by csj1012 — APPROVED** [review]
This LGTM - please resolve the merge conflicts (or ping me if you can't) and then I'm all good to merge.

**Pull request merged**
