### PR TITLE
EWL-6527 homepage membership block spacing and margins

### PR DESCRIPTION
**Pull request by designerneil**
## JIRA Ticket(s)
- [EWL-6527: Homepage Member Feature Updates
](https://issues.ama-assn.org/browse/EWL-6527)

## Description:
Desktop | Reduce spacing between 3 vertical stubs on the right side of the component
Desktop, Tablet | The gray background of div.ama_member-feature-rail should expand further behind the image/content of div.ama_hero-story (see screenshots, Zeplin, tablet Zeplin)
Mobile | Two of the Article Stubs in div.ama__member-feature-rail should appear on mobile, stacked below as seen in the mobile Zeplin

## To Test:
- switch your SG2 branch to `bugfix/EWL-6499-membership-needs-more-sepacing`
- `gulp serve`
- enable local SG2 in your D8 in your local.yml 
- do a `scripts/build` outside your vagrant
- visit http://ama-one.local/
- `drush @one.local cr`
- observe the spacing around the membership block matches zeplin
desktop: https://app.zeplin.io/project/59dd1f9c36a8b21d569bb9e8/screen/5b313db4a1cee6697422dd24
mobile: https://app.zeplin.io/project/59dd1f9c36a8b21d569bb9e8/screen/5b32bd0adf510ffb4747954d

## Automated Test:
n/a

## Relevant Screenshots/GIFs:
screen shot 2018-11-05 at 2 20 01 pm
screen shot 2018-11-05 at 2 20 21 pm

## Additional Notes:
n/a

---

[Pull Request Guidelines](https://github.com/palantirnet/development_documentation/blob/master/guidelines/pr_review.md)

### CODE REVIEW

**Review by damontgomery — CHANGES_REQUESTED** [review]
I updated the description to point to EWL-6527 since I think that's what this was about.

The large image seems to overlap the small images in my test.

overlap_issue

I'm also seeing mobile issues:

There is an overlap at the top

mobile_overlap

The two right rail teasers are vertically stacked rather than side by side

vertical-not-side-to-side

To test this I made a new branch from `develop`, merged in this PR, and ran `gulp`. Then I loaded the homepage on my local machine.

**Comment by designerneil** [comment]
@damontgomery the weird overlapping of images only happened when you were logged as admin. I was testing the page assuming both the logged in and logged out states were the same. Please try again. I think I have addressed the issue

**Review by damontgomery — CHANGES_REQUESTED** [review]
There are two issues.

The spacing to the top and left of the right should be removed.

spacing_should_be_removed

The mobile article stubs should be side by side not in a vertical stack.

stacking

I tested this by making a new branch from `develop` and merging in this branch. I then ran gulp and tested with test D8 content. I tested as the administrator user and as an anonymous user.

**Comment by designerneil** [comment]
@damontgomery padding and mobile view resolved. Thanks!

**Review by damontgomery — CHANGES_REQUESTED** [review]
The other issues are resolved, but there are two new issues.

There is a space above the large image

space-above-large-image

On mobile, the view more should be right aligned and full width (not wrapping)

mobile-view-more

This was tested with a new branch from `develop` with the code merged in. I tested on the D8 site with anonymous and administrator users.

**Comment by designerneil** [comment]
@damontgomery I really don't like this story. Thank you for your thoroughness. I have eliminated the gap and right aligned the link

**Review by damontgomery — APPROVED** [review]
This looks as described.

Tested as anonymous and administrative user.

**Pull request merged**
