### PR TITLE
EWL-6809 individual panel scrolling

### PR DESCRIPTION
**Pull request by designerneil**
## Ticket(s)

**Jira Ticket**
- [EWL-6809: A1 | Resource Page Individual Panel Scrolling](https://issues.ama-assn.org/browse/EWL-6809)

## Description
UX has asked that only the individual columns on the resource page scroll. The footer needs to be moved into the left column at the bottom of the article. The column scrolling will only occur on desktop size viewports

## To Test
- [ ] switch your D8 branch to `feature/EWL-6809-resource-scrolling` (PR https://github.com/AmericanMedicalAssociation/ama-d8/pull/1231)
- [ ] enable local SG2 testing for D8
- [ ] run `drush @one.local cr`
- [ ] switch your SG2 branch to `feature/EWL-6809-resource-scrolling`
- [ ] `gulp serve`
- [ ] visit http://localhost:3000/patterns/05-pages-resource/05-pages-resource.html
- [ ] observe the page scroll has been disabled and only the article and tab columns scroll
- [ ] visit http://ama-one.local/member-groups-sections/women-physicians/wps-meeting-agenda-important-dates
- [ ] observe the individual columns scroll and not the page
- [ ] Did you test in IE 11?

## Relevant Screenshots/GIFs
n/a

## Remaining Tasks
n/a

## Additional Notes
n/a
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by designerneil** [comment]
This story is blocked by https://issues.ama-assn.org/browse/EWL-6808 - A1 | Resource Page Individual Panel Scrolling

**Review by tcfunk — CHANGES_REQUESTED** [review]
Looks good on desktop. Mobile seems to be missing the footer, though. I don't think the designs are clear on what to do for mobile, except to probably do whatever JAMA is doing? JAMA seems to be including the footer for all tabs on mobile.

**Comment by designerneil** [comment]
@tcfunk the footer should stay on bottom. the individual scrolling should only happen on desktop

**Comment by designerneil** [comment]
Footer has been restored for mobile and tablet views

**Comment by tcfunk** [comment]
@designerneil  Does this need integrated into d8 outside of this PR? I tried checking it with d8 and some things don't seem quite right.

**Comment by designerneil** [comment]
@tcfunk the scrolling work for me in D8

**Review by tcfunk — APPROVED** [review]

**Comment by tcfunk** [comment]
@designerneil hitting approve here but there are a couple merge conflicts

**Pull request merged**
