### PR TITLE
[EWL-4514] SG2 | Fix Visual Regressions in Promo pattern variants and add Pattern Info

### PR DESCRIPTION
**Pull request by chelsiejohnston**
## Ticket(s)

**Jira Ticket**
- [EWL-4514: SG2 | Fix Visual Regressions in Promo pattern variants and add Pattern Info](https://issues.ama-assn.org/browse/EWL-4514)

## Description
**This PR is the SG2 counterpart to https://github.com/AmericanMedicalAssociation/ama-d8/pull/274. It needs to be merged before that PR is merged. These PRs should be tested and merged alongside one another (as in, one should not be merged without the other).**

- Fixes the Promo pattern and its variants so that they align with the project requirements. 
- Adds/corrects the Pattern Info for these patterns.

## To Test
`gulp serve`

- [ ] When I click "molecules" in the SG2 menu
--- Then I should see "Promo"
--- And when I click "Promo" 
--- Then I should see that the styling looks correct according to the attached screenshot
--- And I should see that the pattern title is "Promo" and NOT "Promotion"
--- And when I click "Pattern Info" in the Gear Icon menu
--- Then I should see a list of the pattern's variants
--- And I should see that the info in the `.md` file is correct (.json data structure, etc.)

- [ ] And when I click  "molecules" in the SG2 menu again
--- Then I should see "Promo with Border"
--- And when I click "Promo with Border"
--- Then I should see that the styling looks correct according to the attached screenshot
--- And when I click "Pattern Info" in the Gear Icon menu
--- Then I should see information about the pattern and a link back to the "Promo" base pattern

- [ ] And when I click "molecules" in the SG2 menu again
--- Then I should see "Promo with CTA"
--- And when I click "Promo with CTA"
--- Then I should see that the styling looks correct according to the attached screenshot
--- And I should see a full width button is being displayed with style *secondary* (transparent button with border)
--- And when I click "Pattern Info" in the Gear Icon menu
--- Then I should see information about the pattern and a link back to the "Promo" base pattern

- [ ] And when I click "molecules" in the SG2 menu again
--- Then I should see "Promo with Image"
--- And when I click "Promo with Image"
--- Then I should see that the styling looks correct according to the attached screenshot
--- And when I click "Pattern Info" in the Gear Icon menu
--- Then I should see information about the pattern and a link back to the "Promo" base pattern

- [ ] And when I click "pages" in the SG2 menu
--- And when I click "topic"
--- Then I should see a "Promo with CTA" in the left sidebar under Tools

## Visual Regressions
I added scenarios to `backstop.json` for the Promo, Promo with Border, and Promo with CTA variants. Some of the references images did not generate, so I may need someone to run `backstop test` when pulling down the branch and then use `backstop approve` to commit the missing reference images.

Backstop test run on this branch did not show any unexpected regressions in existing tests for patterns.

## Relevant Screenshots/GIFs
Promo 
screen shot 2018-02-22 at 3 28 11 pm

Promo with style Border
promoborder

Promo with style Border and visible CTA
promobordercta

Promo with style Background
promobackground

Promo with style Background and visible CTA
promobackgroundcta

Promo with Image
screen shot 2018-02-22 at 3 29 44 pm

## Remaining Tasks
- [x] Make sure this isn't broken in d8 and all the variants still work - see https://github.com/AmericanMedicalAssociation/ama-d8/pull/274
- [x] Add "Promo" to [The Glossary](https://issues.ama-assn.org:8446/confluence/display/DTD/Glossary?src=contextnavpagetreemode) 

## Additional Notes
This PR is the SG2 counterpart to https://github.com/AmericanMedicalAssociation/ama-d8/pull/274 - that PR should be merged alongside this PR. 

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by chelsiejohnston** [comment]
I've marked this `priority` since it blocks https://issues.ama-assn.org/browse/EWL-4512

**Comment by designerneil** [comment]
let's start out the testing with a `gulp serve`

> And I should see that the pattern title is "Promo" and NOT "Promotion"
I see this is an h2 for pattern title

>  Then I should see that the styling looks correct according to the attached screenshot
This should describe what we should be looking out for. Such as:
Observe an organism with a title and paragraph below it in a gray box.

>  And I should see that the info in the .md file is correct (.json data structure, etc.)

Shouldn't this be?
```
{
  "style": string / required
  "heading": {
    "level": string / required
    "text": string / required
    "class": string / optional
  },
  "paragraph" : {
    "text":string / required
  }
}

```
The observation above holds true for all steps listed in the "To Test"

> --- And I should see a full width button is being displayed with style secondary (white button with border)

I don't see a white button. I see transparent button. Did you intend to have a white button?

**Comment by designerneil** [comment]
Should we have a default margin around the promo organism so they don't touch when we put them on the page?

**Comment by designerneil** [comment]
I get backstop failures for the topic page:
screen shot 2018-02-21 at 9 30 35 am

**Comment by labbydev** [comment]
@chelsiejohnston in your testing instructions please ensure that your screenshots are accurate and labelled accordingly. I have noticed the following issues during my review:
* I do not see a screenshot attached for the default "Promo"
* It looks like the screenshot labels are incorrect for "Promo with Background" and "Promo with Background CTA"
* I do not see a screenshot for "Promo with Image"

**Comment by labbydev** [comment]
@chelsiejohnston I notice these additional items are in the SG2 menu under "molecules" but you do not address them here, can you validate that these are correct and still necessary?
* Promo Email Subscription
* Promo image without CTA description
* Promo logo with white background

**Comment by labbydev** [comment]
> Some of the references images did not generate, so I may need someone to run backstop test when pulling down the branch and then use backstop approve to commit the missing reference images.

It looks like some images are missing or out of date, please ensure that the screenshots are present and correct for canon.

**Comment by labbydev** [comment]
I do agree with @designerneil, that the promo probably needs a default `margin-bottom` that matches that which is currently on the membership block.

**Comment by labbydev** [comment]
I believe that the transparent button is the correct choice, @chelsiejohnston please confirm. It seems like the testing instructions here may be incorrect.

**Comment by labbydev** [comment]
@chelsiejohnston for the sake of being concise here:
> value must be either "background" or "border"

Please update as `options: "background", "border"`

It also looks like the `json` should be showing required or optional and the format expected, instead of the actual `json` is this a change we intend to make to our process? This is based on comparison of `json` notes in `md` files such as that of http://localhost:3000/?p=molecules-article-stub.

**Comment by chelsiejohnston** [comment]
> I notice these additional items are in the SG2 menu under "molecules" but you do not address them here, can you validate that these are correct and still necessary?
> Promo Email Subscription
> Promo image without CTA description
> Promo logo with white background

These are removed in https://github.com/AmericanMedicalAssociation/ama-style-guide-2/pull/118.

I made the rest of the edits mentioned above to the `.md`s, the instructions in the PR, and the code. 

The last thing I'm waiting on is being able to update the backstop reference images. I've tried several things to get this to work without success, so I notified @labbydev about it. Otherwise, this is ready to go (not sure what next steps are without the backstop stuff, I'm just writing this here for reference)

**Comment by designerneil** [comment]
@chelsiejohnston I see a duplicate molecules directory in the patterns folder
screen shot 2018-02-26 at 11 12 50 am

**Comment by designerneil** [comment]
promo.md

~~~
{
  style: "background", (required, options: "background", "border")
  heading: {
    **level: "2"** <--- this should be integer / required
    text: 
      type: string / required
    **class: "ama__h2"** <--- this should be string / required and indented
  }
  paragraph: {
    text: 
      type: string / required
  }
}

**Comment by labbydev** [comment]
@designerneil I do not see duplicated `molecules` directories

**Comment by designerneil** [comment]
weird. it must have been an artifact.

**Review by labbydev — APPROVED** [review]

**Comment by designerneil** [comment]
@labbydev if you're cool with not updating the PR with my comments above. Then let's merge

**Review by designerneil — APPROVED** [review]

**Pull request merged**
