### PR TITLE
EWL-5527 homepage feedback

### PR DESCRIPTION
**Pull request by designerneil**
## Ticket(s)

**Jira Ticket**
- [EWL-5527: A1 | Style Guide - People Homepage Feedback](https://issues.ama-assn.org/browse/EWL-5527)

## Description
Update homepage based on feedback from UX.

Feedback notes can be found here:
https://docs.google.com/spreadsheets/d/1oRKGgOD_hSRrp0CIM1XFIS4PjEHE1-ELxVijV3pbHV8/edit#gid=0

**Please see additional notes about buttons being all caps.**

--
- Delivery Care” should be “Delivering Care
- About, Delivering Care, Practice Mgmt, etc. and Board of Trustees, House of Delegates, etc. links have no hover interaction (Our fault, wasn’t in notes. We can talk through those)
- There should be a divider line between the top two and bottom two articles in the group of 4 on the right next to the hero story.
- Divider lines and padding missing between stories on mobile (spacing on JAMA looks great)
- JAMA component – there were supposed to be specific line breaks for each article with a red hover effect – not the consistent red line as it shows. Padding below also needs to be fine-tuned
- Buttons all have a weird hover effect. They should just go to hover purple. No underline.
- All buttons should be CAPS
- Membership Moves Medicine – padding at top and bottom need fine-tuning.
- “View More from MMM series should be Closer to the bottom of the gray background.
- Check image sizes. They should be 2:3, but I think are currently 3:4
- Explore Topics section header is missing
- “View all topics” text size should be 14, not 10 as it appears
- The promos were supposed to have an overlay. We worked through this in one of the meetings, so I’ll make sure we all understood what was supposed to happen with those.
- Your Products – besides linking “Learn More” we should also link the product titles (JAMA Network, CPT, etc.)
- Upcoming Events. If text should wrap on events, it should be aligned with the text on top and not the purple icon.
- Can spacing be increased between the product name and the description?
- The font on the membership promo should be regular – not semibold/bold
- Page is missing the mission at the bottom of the page. – This is going to be the H1
- Tablet view: Membership moves medicine should only show 2 of the highlighted stories (right now it shows all 3)
- On mobile, “view all events” should not be aligned with the “Your Products” Header. Needs padding.
- On Mobile: “View all Products” should be right aligned.
- Product names should link to products as well as “Learn More”
- As the page responds for smaller devices, instead of stacking when the window gets smaller, all menu items (Product Nav, Category Nav, organizational Nav) should go away. Once the organization nav begins to truncate.

## To Test
- [ ] `gulp serve`
- [ ] visit http://localhost:3000/?p=pages-homepage
- [ ] verify all the items in the description are completed
- [ ] Did you test in IE 11? Yes

## Visual Regressions
All testing is done by Travis
http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/bugfix/EWL-5527-homepage-feedback/html_report/index.html

**See Additional notes below**

## Relevant Screenshots/GIFs
screen shot 2018-07-19 at 4 06 07 pm

## Remaining Tasks
N/A

### All buttons are now in CAPS as requested by UX. 
screen shot 2018-07-19 at 4 36 16 pm

This will cause a lot of backstop failures.

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by labbydev** [comment]
The second and third article stubs at the top are missing the images.

screen shot 2018-07-20 at 3 24 27 pm

**Comment by labbydev** [comment]
I don't see divider lines between these on mobile, should they be there?

screen shot 2018-07-20 at 3 25 07 pm

**Comment by labbydev** [comment]
The font on the membership promo is still bold, also there is a typo here. 

screen shot 2018-07-20 at 3 29 20 pm

**Comment by labbydev** [comment]
This should only show two stories instead of three on tablet. 

screen shot 2018-07-20 at 3 30 35 pm

**Comment by labbydev** [comment]
"View all Events" still seems like it is aligned with "Your Products"

screen shot 2018-07-20 at 3 31 26 pm

**Comment by labbydev** [comment]
View all products should be right aligned on mobile.

screen shot 2018-07-20 at 3 32 29 pm

**Comment by labbydev** [comment]
## Regressions
* It also looks like the uppercase to the buttons is applying all over the site. I don't think this is intended is it? Seems likely that this should only apply to the homepage button.
* The borders on the top of the JAMA components are applying to the JAMA components everywhere, this should be for the homepage only. 
* The default subscribe promo is getting the homepage button and styling and that should only effect the homepage

**Review by labbydev — CHANGES_REQUESTED** [review]
See the comments in the conversation for changes.

**Comment by designerneil** [comment]
@labbydev all button should have uppercase letters. It was request from UX.
screen shot 2018-07-23 at 9 12 52 am

**Comment by designerneil** [comment]
Response:
- It also looks like the uppercase to the buttons is applying all over the site. I don't think this is intended is it? Seems likely that this should only apply to the homepage button.
**Fixed**

- The borders on the top of the JAMA components are applying to the JAMA components everywhere, this should be for the homepage only.
**Will Fix**

- The default subscribe promo is getting the homepage button and styling and that should only effect the homepage
**Will fix.**

**Comment by designerneil** [comment]
@labbydev the tablet size I'm looking at is the 700px wide. That shows only two stories for me. Is this true for you?

**Comment by labbydev** [comment]
@designerneil there are still a couple of issues here:
* The default promo button should be centered and not all caps
screen shot 2018-07-23 at 2 34 44 pm

* The section title should not be full-width on smaller breakpoints, it should be `inline-block` (see Upcoming Events is rendering correctly but Your Products is not)
screen shot 2018-07-23 at 2 36 00 pm

**Comment by labbydev** [comment]
@designerneil there is still a regression in the subscribe promo and also now the "View all products" is back on the left aligned instead of right aligned.

**Comment by designerneil** [comment]
@labbydev i think we have some confusion on the changes here. Can we meet tomorrow and finish this PR?

**Comment by labbydev** [comment]
Yes

**Comment by labbydev** [comment]
@designerneil it looks like the fix to the put the “View all Products” on the right is causing the “Your Products” on mobile to be full-width. Instead of using flexbox we may want to consider using a float or just text-align for this.

In regards to the promo the button weight is still heavier than it should be. Compare against [`gh-pages`](https://americanmedicalassociation.github.io/ama-style-guide-2/?p=molecules-subscribe-promo)

**Comment by designerneil** [comment]
screen shot 2018-07-24 at 1 43 13 pm
screen shot 2018-07-24 at 1 43 01 pm

**Review by labbydev — APPROVED** [review]

**Pull request merged**
