### PR TITLE
EWL-5439: Create category nav organism

### PR DESCRIPTION
**Pull request by labbydev**
## Ticket(s)
**Jira Ticket**
- [EWL-5439: Create Category Nav Organism](https://issues.ama-assn.org/browse/EWL-5439)

## Description
Create category nav and place it on the homepage stub pattern.

## To Test
- [ ] `gulp serve`
- [ ] Click "Organisms" in the menu
- [ ] Observe you see "Category Nav"
- [ ] Click "Category Nav"
- [ ] Observe you see inline links and they are `$homepagePurple`, Myriad Pro Bold
- [ ] Click "Pages" in the menu
- [ ] Click "Homepage"
- [ ] Observe you see the Category Nav in the `pageContent` region of the Homepage
- [ ] Did you test in IE 11? Yes

## Visual Regressions
I added a new scenario to backstop for the category nav.

[Travis Backstop Report](http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/feature/EWL-5439-category-nav/html_report/index.html)

## Relevant Screenshots/GIFs
screen shot 2018-07-11 at 5 10 26 pm

## Remaining Tasks
N/A

## Additional Notes
N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by designerneil** [comment]
Question: the mobile size look and feel is confirmed by the UX to be what they want?

**Comment by labbydev** [comment]
@designerneil they have not designed any of the navs for mobile as of yet. Which is to say, no, but since we haven't been delivered requirements I assume that these will be included or decided when we see the rest of the responsive menu structure.

**Review by JaeBea — CHANGES_REQUESTED** [review]
Hi @labbydev ,

The category nav does not have json data defined in homepage.json so it is not showing up on the page.

**Comment by designerneil** [comment]
@labbydev the nav should disappear on mobile according to the UX team
screen shot 2018-07-13 at 4 07 20 pm

The UX team has indicated that they had this from the beginning.

**Pull request merged**
