### PR TITLE
EWL-3505 Visual Regression Testing with Travis

### PR DESCRIPTION
**Pull request by labbydev**
## Ticket(s)
**Jira Ticket**

- [EWL-3503: Visual Regression Testing in SG2](https://issues.ama-assn.org/browse/EWL-3503)

## Description
Setup travis to run visual regression tests via BackstopJS in SG2

## To Test
- [ ] `npm install`
- [ ] `gulp test`
- [ ] Observe that you see the test results
---
- [ ] `gulp serve`
- [ ] In another terminal tab (or while gulp is running) `backstop test` 
  This will run the visual regression tests locally
- [ ] In another terminal tab (or while gulp is running) `backstop approve`
  If there are deviations this will create new screenshots and set those as the new standard.

## Visual Regressions
N/A

## Relevant Screenshots/GIFs
N/A

## Remaining Tasks
This only includes one visual regression test. We need to add a ticket to create the tests for any already present components. 
Ticket - https://issues.ama-assn.org/browse/EWL-4499

## Additional Notes
For backstop documentation please refer to: https://github.com/garris/BackstopJS

### CODE REVIEW

**Review by designerneil — APPROVED** [review]

**Comment by designerneil** [comment]
When I run backstop test I get fail:
screen shot 2018-01-25 at 3 32 59 pm

**Comment by designerneil** [comment]
Can we also put a git ignore on the bitmaps and pngs that are created by backstop?

screen shot 2018-01-25 at 3 54 44 pm

**Comment by labbydev** [comment]
@designerneil what does it do when you try to run `backstop approve`? It looks like backstop is running at some point so I'm not sure why it's failing. What does the report say? I'm committing the images intentionally because that is what Travis will need to compare against and we want to make sure that the committed ones for each new component are visually correct so that when we run the tests we know they are being compared against the correct visuals.

**Comment by designerneil** [comment]
@labbydev when i run backstop test i get an error:
```
See: /Users/ngallagh/projects/ama-style-guide-2/styleguide/backstop_data/bitmaps_test/20180131-105938/failed_diff_backstop_default_atoms-button_0_sg-viewport_0_bp-xs.png
   See: /Users/ngallagh/projects/ama-style-guide-2/styleguide/backstop_data/bitmaps_test/20180131-105938/failed_diff_backstop_default_atoms-button_0_sg-viewport_1_bp-small.png
      compare | ERROR { requireSameDimensions: false, size: isDifferent, content: undefined%, threshold: 1% }: atoms-button backstop_default_atoms-button_0_sg-viewport_0_bp-xs.png
      compare | ERROR { requireSameDimensions: false, size: isDifferent, content: undefined%, threshold: 1% }: atoms-button backstop_default_atoms-button_0_sg-viewport_1_bp-small.png
   See: /Users/ngallagh/projects/ama-style-guide-2/styleguide/backstop_data/bitmaps_test/20180131-105938/failed_diff_backstop_default_atoms-button_0_sg-viewport_2_bp-med.png
   See: /Users/ngallagh/projects/ama-style-guide-2/styleguide/backstop_data/bitmaps_test/20180131-105938/failed_diff_backstop_default_atoms-button_0_sg-viewport_3_bp-large.png
      compare | ERROR { requireSameDimensions: false, size: isDifferent, content: undefined%, threshold: 1% }: atoms-button backstop_default_atoms-button_0_sg-viewport_2_bp-med.png
   See: /Users/ngallagh/projects/ama-style-guide-2/styleguide/backstop_data/bitmaps_test/20180131-105938/failed_diff_backstop_default_atoms-button_0_sg-viewport_4_bp-xl.png
      compare | ERROR { requireSameDimensions: false, size: isDifferent, content: undefined%, threshold: 1% }: atoms-button backstop_default_atoms-button_0_sg-viewport_3_bp-large.png
      compare | ERROR { requireSameDimensions: false, size: isDifferent, content: undefined%, threshold: 1% }: atoms-button backstop_default_atoms-button_0_sg-viewport_4_bp-xl.png
       report | Test completed...
       report | 0 Passed
       report | 5 Failed
       report | Writing browser report
       report | Resources copied
       report | Copied configuration to: /Users/ngallagh/projects/ama-style-guide-2/styleguide/backstop_data/html_report/config.js
      COMMAND | Executing core for `openReport`
   openReport | Opening report.
       report | *** Mismatch errors found ***
      COMMAND | Command `report` ended with an error after [2.026s]
      COMMAND | Command `test` ended with an error after [6.529s]
```

**Comment by designerneil** [comment]
@labbydev when i run gulp backstop then backstop approve i get:
```
eport | Test completed...
       report | 0 Passed
       report | 5 Failed
       report | Writing browser report
       report | Browser reported copied
       report | Copied configuration to: /Users/ngallagh/projects/ama-style-guide-2/styleguide/backstop_data/html_report/config.js
      COMMAND | Executing core for `openReport`
   openReport | Opening report.
       report | *** Mismatch errors found ***
      COMMAND | Command `report` ended with an error after [1.947s]
      COMMAND | Error: Mismatch errors found.
                    at /Users/ngallagh/projects/ama-style-guide-2/styleguide/node_modules/backstopjs/core/command/report.js:113:17
                    at process._tickCallback (internal/process/next_tick.js:109:7)
      COMMAND | Command `test` ended with an error after [6.329s]
      COMMAND | Error: Mismatch errors found.
                    at /Users/ngallagh/projects/ama-style-guide-2/styleguide/node_modules/backstopjs/core/command/report.js:113:17
                    at process._tickCallback (internal/process/next_tick.js:109:7)
[11:01:33] 'backstop' errored after 7.16 s
```

**Comment by chelsiejohnston** [comment]
@labbydev before I take a look, please:

- resolve merge conflicts
- add a link to the ticket for creating the tests for the existing patterns

**Comment by labbydev** [comment]
@chelsiejohnston I've added a link to the ticket in the Remaining tasks and have resolved the merge conflicts.

**Comment by labbydev** [comment]
@designerneil do you have `gulp serve` running when you're running `backstop test`? This will cause it to error since it needs to see the component in order to test it.

**Comment by designerneil** [comment]
@labbydev I don't have gulp running when executing backstop test

screen shot 2018-02-01 at 3 27 17 pm

**Pull request merged**
