### PR TITLE
[EWL-4936] Resource and Resource Tabs QA fixes

### PR DESCRIPTION
**Pull request by csj1012**
## Ticket(s)

**Jira Ticket**
- [EWL-4936: SG2 | Create "Resource Tabs" Organism and insert into Resource page](https://issues.ama-assn.org/browse/EWL-4936)
- [EWL-5050: QA/EWL- 4936 SG2 | Create "Resource Tabs" organism and insert into Resource page](https://issues.ama-assn.org/browse/EWL-5050)

## Description
- Replaces promo molecules with membership molecules where needed.
- Adds a `resource-tabs.json` to supply data to the Resource Tabs organism when viewed on its own.
- Updates the relevant backstop images.

## To Test
- [ ] `gulp serve`
- [ ] Click the Media tab and confirm that you see: 
  - [ ] Youtube embed
  - [ ] Small Text under video embed
  - [ ] Membership molecule
  - [ ] Image molecule
- [ ] Click the Downloads tab and confirm that you see:
  - [ ] "Download 1" heading
- [ ] Click the Tables tab and confirm that you see:
  - [ ] "Table 1" heading
  - [ ] Table atom
- [ ] Generally, make sure no data seems to be missing from what's on ghpages SG2

## Visual Regressions

- [x] **Before proceeding:** Run visual regression tests locally to ensure new work does not introduce new bugs.

- [x] _If the new work does your work introduce visual regressions into existing work in the Style Guide (or in a Drupal 8 environment)_, either call these out here or address them before marking the PR as `ready for review`.

- [x] If you are creating or updating a pattern be sure you have created or updated the [scenario in `backstop.json`](ama-style-guide-2/styleguide/backstop.json) and have included a new or updated screenshot in [`bitmaps_reference`](ama-style-guide-2/styleguide/backstop_data/bitmaps_reference).

## Relevant Screenshots/GIFs
Media tab:
> screen shot 2018-05-24 at 2 23 01 pm

Downloads tab:
> screen shot 2018-05-24 at 2 23 05 pm

Table tab:
> screen shot 2018-05-24 at 2 23 12 pm

## Remaining Tasks
N/A

## Additional Notes
Ran into errors when trying to include `membership.twig` using anything other than `{% set %}` and defining the whole array in the twig file (running into issues given the use of `|merge()` Twig filter). IMO we should address this in https://issues.ama-assn.org/browse/EWL-5018

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Review by JaeBea — CHANGES_REQUESTED** [review]
@chelsiejohnston  Looks good, only need one thing before I can merge.

Please add a membership promo block to the downloads tab as noted in the original ticket and test case/qa ticket.

**Comment by csj1012** [comment]
@JaeBea I've added the membership block there, but now there's an array to string error and I'm not sure why. Would you mind checking to see if you can also see it in your env?

**Comment by JaeBea** [comment]
@chelsiejohnston You are looping through everything in the `tabContent.downloads` object in your twig and it is no longer all the same content. So it goes through `download1` - `download3`, hits `membership`, and then tries to cough up the tool molecule with membership molecule content. That is where your error is occurring.

**Comment by JaeBea** [comment]
@chelsiejohnston Review of this PR is pending merge of PR #282. The develop branch will need to be merged in again.

**Comment by designerneil** [comment]
@chelsiejohnston the merge conflict is only Backstop ref images. Just run backstop test and that should resolve the merge conflict

**Review by JaeBea — APPROVED** [review]
The requested updates have been dealt with and merge conflicts resolved. The backstop test failures that I am seeing are from develop branch and thus unrelated to this PR so I will approve and merge.

**Comment by Brian-Clement** [comment]
Merging for @JaeBea

**Pull request merged**
