### PR TITLE
[EWL-5442] SG2 | Create "JAMA as Homepage" variant

### PR DESCRIPTION
**Pull request by csj1012**
## Ticket(s)

**Jira Ticket**
- [EWL-5442: SG2 | Create "JAMA as Homepage" variant](https://issues.ama-assn.org/browse/EWL-5442)

## Description
Adds JAMA molecule variant to the home page.

## To Test
- [ ] `gulp serve`
- [ ] Given that I am viewing SG2
- [ ] When I click "Molecules"
- [ ] Then I should see "JAMA"
- [ ] When I click "JAMA"
- [ ] Then I should see "JAMA as Homepage"
- [ ] And should see 4 columns of links with the Jama logo on top
- [ ] When I resize the browser to mobile
- [ ] I should see the columns collapse and the links stack
- [ ] When I click "Pages"
- [ ] Then I should see "Homepage"
- [ ] When I click "Homepage"
- [ ] Then I should see the "JAMA as Homepage" with the expected styling
- [ ] Did you test in IE 11?

## Visual Regressions

All testing is done by Travis
http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/feature/EWL-5442-create-jama-as-homepage-variant/html_report/index.html

Please review the above backstop report to see if only expected changes are in it

## Relevant Screenshots/GIFs
screen shot 2018-07-13 at 2 06 23 pm
screen shot 2018-07-13 at 2 00 28 pm

## Remaining Tasks
N/A

## Additional Notes

>Should be exactly the same as the sidebar but only horizontal. Should only be based on the fact that is placed on the homepage

The ticket says this, but the comp shows a slight difference in styling. This will need to be confirmed with UX.

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by designerneil** [comment]
And I should NOT see the expected styling, as it will be visible on the Homepage Page

Yet I do:
screen shot 2018-07-13 at 11 02 06 am

Did you mean?
 And I should NOT see the expected styling of the links in columns?
or 
Should be exactly the same as the sidebar but only horizontal. Should only be based on the fact that is placed on the homepage.

**Comment by designerneil** [comment]
According to the mockup the line below the links should be red. The current implementation has it gray.

**Current**
screen shot 2018-07-13 at 11 06 07 am


**Zeplin**
screen shot 2018-07-03 at 9 56 28 am

**Comment by designerneil** [comment]
On mobile the links don't stack.
  
**Current**
screen shot 2018-07-13 at 11 08 44 am

**Zeplin**
screen shot 2018-07-13 at 11 09 15 am

**Review by JaeBea — APPROVED** [review]
@nstriedinger ,

This looks good to go!

**Pull request merged**
