### PR TITLE
[EWL-5306] SG2 | Fix Broken Molecule Twig Templates

### PR DESCRIPTION
**Pull request by JaeBea**
## Ticket(s)

**Jira Ticket**
- [EWL-5306: SG2 | Fix Broken Molecule Twig Templates](https://issues.ama-assn.org/browse/EWL-5306)

## Description
Multiple bugs have been introduced into the `develop` branch of SG2 which has caused templates includes of various molecules to not render correctly.

This update corrects template include paths from previous molecule template reorganizing. All backstop reference image issues introduced from the reorganizing as been included in this PR.

Chromy errors were resolved with updates to backstop test cases that were not able to find the correct pattern lab pages.

## To Test
- Pull `bugfix/EWL-5306-broken-twig-templates` branch
- Run `gulp serve` in ama-style-guide-2/styleguide to ensure a local version of style guide is running.
- Run `backstop test` and confirm no errors occur.
- Visit all pages and organisms to confirm there are no errors with template include paths.

## Visual Regressions

Updates to reference images have been included in this PR.

## Relevant Screenshots/GIFs
N/A

## Remaining Tasks
N/A

## Additional Notes
N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by labbydev** [comment]
@JaeBea I can't run `gulp serve` on this branch. Are you using the same versions outlined in the `README.md`?

I removed `node_modules` and re-ran `npm install`. This is the result of running `gulp serve`:
```
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1345:14)
    at listenInCluster (net.js:1386:12)
    at Server.listen (net.js:1474:7)
    at module.exports.plugin (/Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/node_modules/browser-sync/dist/server/index.js:27:25)
    at Object.startServer [as fn] (/Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/node_modules/browser-sync/dist/async.js:177:52)
    at /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/node_modules/browser-sync/dist/browser-sync.js:120:14
    at iterate (/Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/node_modules/browser-sync/dist/utils.js:253:13)
    at /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/node_modules/browser-sync/dist/utils.js:264:25
    at executeTask (/Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/node_modules/browser-sync/dist/browser-sync.js:136:13)
    at Object.mergeMiddlewares [as fn] (/Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/node_modules/browser-sync/dist/async.js:166:9)

Emitted 'error' event at:
    at emitErrorNT (net.js:1365:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```

**Comment by JaeBea** [comment]
Yes, I am using v9.9.0. I re-installed all node modules after trashing my node_modules folder and could not recreate this issue.

**Comment by csj1012** [comment]
Hi @JaeBea - I'm not 100% of the reliability of these tests but I'm getting a handful of diffs: 

`atoms-search-field - .ama__search__field` - letter spacing or something has changed here, but it could also be a difference in viewport size?
> screen shot 2018-06-07 at 4 38 37 pm


`press-release-logos - .ama__press-release__logos` - test can't find reference URLs or images?
> screen shot 2018-06-07 at 4 38 42 pm


`organisms-footer - .ama__footer` - some padding has changed?
> screen shot 2018-06-07 at 4 38 53 pm


`event listing - document` - there's some change in the padding under the event card (?) but also the same change in the search field
> screen shot 2018-06-07 at 4 39 24 pm

**Review by csj1012 — CHANGES_REQUESTED** [review]
I'm getting some perplexing backstop failures.

**Comment by JaeBea** [comment]
@chelsiejohnston I Am not getting these errors when I run backstop on my local. I am going to set this as blocked while reviewing PR #283 . I believe there is something buggy with our set up. Neil's PR updates backstop test cases and changes the engine to puppeteer. I will merge that into this one once it is approved and see if we continue to have the differing problems.

**Comment by JaeBea** [comment]
@labbydev and @chelsiejohnston This PR has been updated to include backstop changes recently merged into develop.

**Review by labbydev — CHANGES_REQUESTED** [review]
@JaeBea I'm getting a failure in the backstop tests. I actually think the failure is the correct version based on the Drupal theming. Regardless, please address this.

screen shot 2018-06-13 at 4 43 37 pm

**Comment by JaeBea** [comment]
@labbydev I have corrected test cases so that default masthead is not overriding masthead with subtitle test. Updated backstop images have been added.

**Review by labbydev — APPROVED** [review]

**Pull request merged**
