### PR TITLE
update backstop screenshots

### PR DESCRIPTION
**Pull request by labbydev**
## Ticket(s)
**Do not** submit a Pull Request without a relevant JIRA ticket or Github issue! If you are creating a new pattern or feature, create an issue describing the need for this feature in Github **first** and then link to it below.

**Github Issue**
N/A

**Jira Ticket**
N/A

## Description
Fix failing backstop tests on develop by updating the test images to reflect reality.

## To Test
- [ ] `gulp serve`
- [ ] Open another terminal windo
- [ ] `backstop test`
- [ ] Observe VRT passes

## Visual Regressions
N/A

## Relevant Screenshots/GIFs
N/A

## Remaining Tasks
N/A

## Additional Notes
N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Review by JaeBea — CHANGES_REQUESTED** [review]
Hi @labbydev ,
Looks good except for one thing. Could you update the test case for `resource tabs` to ignore iframes? I am getting one failure from the youtube video.
image

**Comment by designerneil** [comment]
@labbydev the same here
screen shot 2018-07-02 at 10 18 04 am

**Comment by labbydev** [comment]
I have updated the resource tabs configuration and screenshots.

**Review by JaeBea — APPROVED** [review]
@labbydev, I am no longer getting any backstop errors. This looks good to go.

**Pull request merged**
