### PR TITLE
EWL-7176 Remove Menu Expansion Scroll Bars

### PR DESCRIPTION
**Pull request by designerneil**
## Ticket(s)
**Do not** submit a Pull Request without a relevant JIRA ticket or Github issue! If you are creating a new pattern or feature, create an issue describing the need for this feature in Github **first** and then link to it below.

**Jira Ticket**
- [EWL-7176 Remove Menu Expansion Scroll Bars](https://issues.ama-assn.org/browse/EWL-7176)

## Description
When the AMA purple banner is sticky the main menu gets cut off if the viewport is too small. When the submenu with article stubs it also is cut off when the viewport is too small. As a user I would like the menus and the articles to be scrollable when my viewport is too small to see all of it.

## To Test
- [ ] switch your SG2 branch to `feature/EWL-7176-Remove-Menu-Expansion-Scroll-Bars`
- [ ] run `gulp serve`
- [ ] visit http://localhost:3000/patterns/05-pages-homepage/05-pages-homepage.html#
- [ ] resize your window so that the dropdown menu from the banner is cut off
- [ ] observe the dropdown main menu is scrollable
- [ ] mouseover the categories
- [ ] make sure the category submenu with article stub is cut off by the viewport
- [ ] scroll inside the submenu
- [ ] observe that the content is scrollable
- [ ] Did you test in IE 11?

## Relevant Screenshots/GIFs
Screen Shot 2019-05-03 at 12 48 45 PM

## Remaining Tasks
n/a

## Additional Notes
n/a
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Review by JaeBea — CHANGES_REQUESTED** [review]
@designerneil ,
- The page scrollbar appears and then disappears when scrolling within the menu in both D8
- The top of the white panel is hidden until you move your mouse inside of it in both D8 and SG2.
-  I am getting some weird flickering when I have hover inside of the white menu panel in SG2.

I have linked screen recordings of what I am seeing below.

[Menu scrolling in D8](https://drive.google.com/open?id=15fYtVqBI6jaFXc51V7HsrcPLLlN_MfQ5)
[Menu scrolling in SG2](https://drive.google.com/open?id=1gVsPTf11WzJC-lh7MI6xT_kek43htR3j)

**Comment by designerneil** [comment]
@JaeBea I think I took care of all the issues including the menu getting clipped by the main nav.

**Review by JaeBea — CHANGES_REQUESTED** [review]
@designerneil ,
The white menu panel is not properly vertical aligning in the center or at the top of the viewable area in D8 for `About` and `Member Groups`. I've tested this in Chrome and IE11.

Screen Shot 2019-05-06 at 11 17 46 AM

**Comment by designerneil** [comment]
@JaeBea thanks. I fixed the two flyouts that were not getting positioned correctly.

**Comment by designerneil** [comment]
@JaeBea merge conflict resolved

**Review by JaeBea — CHANGES_REQUESTED** [review]
@designerneil ,
Most recent changes have introduced an issue with the white panel being disconnected from the parent link item hover effect. The screenshot below is what happens when I hover over education category.

image

**Review by JaeBea — APPROVED** [review]
@designerneil ,
My feedback has been addressed. I will merge into develop.

**Pull request merged**
