### PR TITLE
EWL-8371: Adding Missing padding for Tools & Resources according specs

### PR DESCRIPTION
**Pull request by acidaniel**
**Jira Ticket**
- [EWL-8371: Subcat | Essential Tools & Resources Block link padding is incorrect](https://issues.ama-assn.org/browse/EWL-8371)

## Description
* Adding only missing padding for tools and resources according specs.

## To Test
- [ ] Checkout this branch and compile assets `lando gulp serve`
- [ ] In Drupal go to a page like: `councils/council-ethical-judicial-affairs` look at the Essential Tools & Resources component
- [ ] Review Padding matches according the specs:
*From jira ticket*:

* 28px to the left of the ET&R title 28 px to the left of the link icon 28 px to the right of the third/furthers right link and container edge ( These three points are 1,2 and 5 from jira ticket on the AC) are solved by the rule that states that the wrapper of `ama_tools` will be based on that padding:

Screen Shot 2020-11-09 at 7 27 02 AM

* 14px between the right of the link icon and link text (point three from jira ticket)
Are solved by the rule that states that `ama__tool_icon` class will have that padding:
Screen Shot 2020-11-09 at 7 29 29 AM

* 21px between right of link text and left of next link icon:
Added on this PR this one was missing, this one is solved by the rule of adding the missing 21px to `ama_tool_text` class:

Screen Shot 2020-11-09 at 7 31 38 AM

## Visual Regressions
N/A

## Relevant Screenshots/GIFs
N/A

## Remaining Tasks
N/A

## Additional Notes
N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Review by joshuathorne — CHANGES_REQUESTED** [review]
- Changes must apply to tools and resources blocks wherever they appear on the site.
- Care must be taken to ensure that styles don't cause regressions when tools & resources is displayed either full width or constrained in a sidebar.
- There should be a mobile style that removes this padding, and the text should be set to wrap properly when it needs to.

**Comment by acidaniel** [comment]
@Dr-Zee Good catch I forgot to add the rule to remove the padding on mobile. This is done, the rest of your comments are so accurate that this is the way currently is working/implemented. These changes will work either the component is used in the sidebar or in the content section. (Just updated the test instructions)

**Review by joshuathorne — CHANGES_REQUESTED** [review]
.ama__subcategory-index {

This will only affect blocks on the subcategory page.

**Comment by acidaniel** [comment]
@Dr-Zee You are right, I just moved the rule to the global component, so the changes will take effect whenever they are displayed.

**Review by joshuathorne — CHANGES_REQUESTED** [review]
> * Changes must apply to tools and resources blocks wherever they appear on the site.
> * Care must be taken to ensure that styles don't cause regressions when tools & resources is displayed either full width or constrained in a sidebar.
> * There should be a mobile style that removes this padding, and the text should be set to wrap properly when it needs to.

@acidaniel  this block appears elsewhere on the site. These rules need to be negated for any time the block is in a sidebar, or in the right side of a two column layout.

**Comment by acidaniel** [comment]
@Dr-Zee Instead of negate the condition, I'm ensuring the styles will apply only to the main content layout, not sidebars. I tested using all layouts, and it is working as expected.

**Review by joshuathorne — APPROVED** [review]

**Pull request merged**
