### PR TITLE
EWL-4558: rename press-release-logos to ama__press-release__logos

### PR DESCRIPTION
**Pull request by designerneil**
## Ticket(s)

**Jira Ticket**
- [EWL-4558: SG2 | Set semantic BEM class on Press Release Logos](https://issues.ama-assn.org/browse/EWL-4558)

## Description
rename press-release-logos to ama__press-release__logos so it meets our naming standards. --logos was changed to __logos in the name because it's a child of the the press-release.

## To Test
- [ ] ` gulp serve`
- [ ] visit http://localhost:3000/?p=molecules-press-release-logos
- [ ] Use Chrome to inspect the logo container 
- [ ] Observe that the class of the element is now named  ama__press-release__logos

## Visual Regressions
`gulp backstop`

## Relevant Screenshots/GIFs
N/A

## Remaining Tasks
N/A

## Additional Notes
N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by designerneil** [comment]
https://github.com/AmericanMedicalAssociation/ama-style-guide-2/pull/115

**Comment by nstriedinger** [comment]
@designerneil Are some tests missing here?

screen shot 2018-02-22 at 2 43 34 pm

**Comment by designerneil** [comment]
@nstriedinger I forgot to update the selector in backstop.json. It should be resolved now.

**Comment by nstriedinger** [comment]
@designerneil  -- something went wrong?

screen shot 2018-02-22 at 3 34 04 pm

**Comment by labbydev** [comment]
This is passing for me. @nstriedinger when running tests are you running `gulp serve` in another terminal window/tab?

**Pull request merged**
