### PR TITLE
EWL-6581 right aligns subscribe button to text input field for mobile and tablet

### PR DESCRIPTION
**Pull request by designerneil**
## Ticket(s)

**Jira Ticket**
- [EWL-6581: Footer - tablet view - right align subscribe button.](https://issues.ama-assn.org/browse/EWL-6581)

## Description
Fix tablet view subscribe buttons needs to right align with the email textfield in the footer

## To Test

D8 
- [ ] switch your branch to `bugfix/EWL-6581-footer-tablet-subscribe`
- [ ] `gulp serve`
- [ ] enable local SG2 in your D8
- [ ] `drush @one.local cr`
- [ ] visit http://ama-one.local/
- [ ] scroll down to the footer
- [ ] resize your browser to tablet size
- [ ] observe the email subscription button is now aligned with the email textfield input

Styleguide update
- [ ] visit http://localhost:3000/?p=pages-homepage
- [ ] scroll to the footer
- [ ] resize your browser to tablet size
- [ ] observe the email subscription button is now aligned with the email textfield input

## Visual Regressions

n/a

## Relevant Screenshots/GIFs
screen shot 2018-11-15 at 2 22 02 pm

## Remaining Tasks
n/a

## Additional Notes
n/a
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by nstriedinger** [comment]
Safari still seems to drop the button.

screen shot 2018-11-16 at 11 06 32 am

**Comment by nstriedinger** [comment]
and on tablet the **Error message** is borked.

screen shot 2018-11-16 at 11 11 31 am

screen shot 2018-11-16 at 11 13 15 am

screen shot 2018-11-16 at 11 14 12 am

**Comment by designerneil** [comment]
@nstriedinger changed height to 37px

**Comment by damontgomery** [comment]
@designerneil I only see one commit here. Is this ready for review?

**Comment by designerneil** [comment]
@damontgomery I can't reproduce @nstriedinger screenshots. Can you take a stab?

**Comment by damontgomery** [comment]
I can't reproduce the safari issue or tablet issues. I tested in Chrome, IE11, and Safari using the Drupal site and the style guide. I tested on a category page.

**Review by damontgomery — APPROVED** [review]
This works for me.

I wasn't able to reproduce the issues Nate was having. I tested on Chrome, Safari, and IE11 using a Drupal category page and the style guide homepage.

**Pull request closed without merging**
