### PR TITLE
EWL-5437: Create "article stub for homepage" molecule

### PR DESCRIPTION
**Pull request by labbydev**
## Ticket(s)
**Jira Ticket**
- [EWL-5437: Create "Article Stub for Homepage"](https://issues.ama-assn.org/browse/EWL-5437)
- [EWL-5436: Create "Article Stub as Hero for Homepage"](https://issues.ama-assn.org/browse/EWL-5436)

## Description
Create some variations of the article stubs that appear on the homepage sections. 

## To Test
- [x] `gulp serve`
- [x] Navigate to SG2
- [x] Click "Molecules" in the menu
- [x] Click "Article Stub" in the dropdown
- [x] Observe you see "Article Stub for Homepage"
- [x] Click "Article Stub for Homepage"
- [x] Observe you see an image
- [ ] Observe you see the Category and it is `$homepagePurple`, Myriad Pro Semibold, 14/15
- [ ] Observe you see the article title and it is Myriad Pro Semibold, 22/26, `$black`
- [x] Observe you see the metadata
- [x] Click "Molecules" in the menu
- [x] Click "Article Stub" in the dropdown
- [x] Observe you see "Article Stub as Hero for Homepage"
- [x] Click "Article Stub for as Hero Homepage"
- [x] Observe you see an image
- [ ] Observe you see the Category and it is `$homepagePurple`, Myriad Pro Semibold, 14/15
- [x] Observe you see the Article title and it is `$black`, Myriad Pro Semibold
- [x] Observe the Article title is 38/44.2 on Desktop
- [x] Observe the Article title is 28/26 on Mobile
- [x] Observe you see the metadata
- [x] Did you test in IE 11? Yes.

## Visual Regressions
Created 2 new scenarios ~and screenshots~ for the two new patterns.

[Travis Backstop Report](http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/feature/EWL-5437-article-stub-homepage/html_report/index.html)

## Relevant Screenshots/GIFs
image

## Remaining Tasks
N/A

## Additional Notes
N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by labbydev** [comment]
@chelsiejohnston this may become a blocker for your work.

**Comment by csj1012** [comment]
Hey @labbydev, this looks great except for a few minor font size differences. Please address:

Article Stub for Homepage:
- [x] Line height for article title text is too small (21.9px)

Article Stub for Homepage as Hero:
- [x] Line height for article title text is too large on mobile (32px)

Both patterns:
- [x] Left margin/padding for category text is not always visually left-aligned with other text
- [x] Font size for category text is too small (10px / 13.8px at all breakpoints for "for Homepage" and 10px / 13.8px at desktop for "for Homepage as Hero")

Font size for category text:
screen shot 2018-07-09 at 8 09 38 pm

Text alignment:
screen shot 2018-07-09 at 8 10 54 pm

**Review by csj1012 — CHANGES_REQUESTED** [review]
See comment.

**Comment by labbydev** [comment]
@csj1012  I noticed the indent/left margin issue on mobile that you point out. This is something that existed within the article stub before I started this work. Should I remove it for the new instances or all instances?

**Comment by csj1012** [comment]
@labbydev I’d say just fix it for the new instances (make it specific to the wrapper) and leave it in the existing stuff it’s an existing problem.

**Comment by labbydev** [comment]
@csj1012 I have removed the screenshots and added a link to the travis results. This should be ready for re-testing.

**Review by designerneil — APPROVED** [review]

**Pull request merged**
