### PR TITLE
EWL-6493 Fix member feature is too big in IE11

### PR DESCRIPTION
**Pull request by designerneil**
## Ticket(s)

**Jira Ticket**
- [EWL-6493: A1 | Homepage member feature image too big in IE11](https://issues.ama-assn.org/browse/EWL-6493)

## Description
Member feature image is too large and the member rail is too spread out in IE11 
dashboard 1

## To Test
- [ ] switch your SG2 branch to 
- [ ] `gulp serve`
- go to your D8 and enable local SG2
- [ ] Did you test in IE 11?

## Visual Regressions

A report is available [here](http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/bugfix/EWL-6493-member-feature-image-too-big-IE11/html_report/index.html).

## Relevant Screenshots/GIFs
N/A

## Remaining Tasks
N/A

## Additional Notes
N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by damontgomery** [comment]
@designerneil, this has a merge conflict now that the other work was done for this component.

**Review by Brian-Clement — COMMENTED** [review]
@designerneil I'm seeing some regression on the tablet viewport size:

image

Could you take a look?

To test, I built this locally on AMA D8 `develop` and used my local SG2.

**Comment by designerneil** [comment]
@Brian-Clement this is what I see
screen shot 2018-11-06 at 8 59 57 pm

**Comment by Brian-Clement** [comment]
@designerneil rotate the tablet to portrait mode.  I'm seeing:
image

**Comment by designerneil** [comment]
screen shot 2018-11-06 at 9 03 28 pm

**Comment by Brian-Clement** [comment]
@designerneil if you scroll down you should see the gap at the bottom of the component.

**Comment by designerneil** [comment]
@Brian-Clement basically there is too much info in the right rail causing the gap on the bottom

**Comment by designerneil** [comment]
@Brian-Clement I think I address the gap issue. Can you check again?

**Comment by mrspete** [comment]
screen shot 2018-11-07 at 12 25 51 am
So here's what i see on tablet portrait view building sg off this branch and using develop.  I don't think this regression is desirable, but it's possible i am just super tired, so i am going to look at it again in the morning.

**Comment by mrspete** [comment]
I merged brian's alt pr

**Pull request merged**
