### PR TITLE
Adf 359 implement suggestions when no results 

### PR DESCRIPTION
**Pull request by payekumi**
**Jira Ticket**
- [ADF-359: Ticket Title](https://palantir.atlassian.net/browse/ADF-359)

## Description
Implement suggestion
 
## Testing Steps

- checkout branch 
- 'Gulp Serve'
- Navigate to Pages > Dr-finder-with-search-no-results

## Relevant Screenshots/GIFs

Screen Shot 2022-12-16 at 3 34 34 PM

## Remaining Tasks
Style "Suggestion"

### CODE REVIEW

**Comment by nstriedinger** [comment]
@payekumi You want to create a new `molecule` called `dr-finder-search-suggestions`

**Comment by nstriedinger** [comment]
@payekumi and @emmacorn Just one thing that we should probably fix. The "Boldness" of the `No Results` heading.

Screen Shot 2022-12-16 at 4 57 58 PM

**Comment by nstriedinger** [comment]
@payekumi @emmacorn Let's bring down the font on mobile to match the `Results for`.

Screen Shot 2022-12-19 at 9 07 56 AM

**Comment by payekumi** [comment]
Currently I am making the mobile changes

**Comment by payekumi** [comment]
I have made the changes requested.

**Pull request merged**
