### PR TITLE
Feature/freida theme

### PR DESCRIPTION
**Pull request by nstriedinger**
## Ticket(s)
**Do not** submit a Pull Request without a relevant JIRA ticket or Github issue! If you are creating a new pattern or feature, create an issue describing the need for this feature in Github **first** and then link to it below.

**Github Issue**
- [Issue XXX: Issue Title](https://github.com/AmericanMedicalAssociation/AMA-style-guide/issues/XXX)

**Jira Ticket**
- [EWL-XXXX: Ticket Title](https://issues.ama-assn.org/browse/EWL-XXXX)

## Description
- Themes FREIDA Specialty 2 Col WYSIWYG
- Fixes exposed sort on FREIDA Specialty View

## To Test
- [x] Link up your AMA One theme with this branch of the style guide
- [x] Create a Specialty node and add a 2 Col WYSIWYG component.  Verify it is styled correctly.
- [x] Create a Specialty Landing page.  Use devel generate to make a ton of Specialty nodes that will appear in the view here.  Use the exposed A-Z / Z-A sorting, confirming it works
- [x] Did you test in IE 11?

## Visual Regressions

_Please provide the pull request ID below. This will then reference the automated VRT report after it has been generated._

A report is available [here](http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/[PULL_REQUEST_ID]/html_report/index.html).

**Before proceeding:** Run visual regression tests locally to ensure new work does not introduce new bugs.

_The visual regression tests always compare against the production version of the style guide. Changes and new work will show up as test failures. Please describe your work so that the report can be reviewed by the team._

If you are creating or updating a pattern be sure you have created or updated the [scenario in `backstop.json`](ama-style-guide-2/styleguide/backstop.json).

_After changes in the report are documented and demonstrate your desired changes, please mark the pull request as `ready for review`.

For more information on visual regression testing review the [How do I run tests?](https://issues.ama-assn.org:8446/confluence/pages/viewpage.action?pageId=23298568) document in Confluence.

## Relevant Screenshots/GIFs
Use something like [Skitch](https://evernote.com/skitch/) or [GIPHY Capture](https://giphy.com/apps/giphycapture) to capture images/gifs to demonstrate behaviors.

## Remaining Tasks
Things relevant to here may be updating [The Glossary](https://issues.ama-assn.org:8446/confluence/display/DTD/Glossary?src=contextnavpagetreemode) with the latest naming changes or review of the relative [D8](https://github.com/AmericanMedicalAssociation/ama-d8) work.

## Additional Notes
Anything more to add? Good things to call out here are:
- are there any PRs in this or other repositories that relate to or affect this PR?
- are there any caveats or oddities testers should know about when testing this PR?
- are there any problems you ran into during your work that you'd like to call out?

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Review by tcfunk — CHANGES_REQUESTED** [review]
@nstriedinger looking good on Chrome. Safari, Firefox, and IE11 all seem to be having trouble with the 2-column layout though
screen shot 2018-12-07 at 11 03 55 am

**Comment by nstriedinger** [comment]
@tcfunk Would you `git pull` and re-visit. Seems to be working in FF and Safari and ie11
screen shot 2018-12-07 at 1 00 51 pm

**Comment by tcfunk** [comment]
@nstriedinger Ok actually...I think I was wrong. It's not a browser issue, it's a logged in vs. logged out issue. The rule for the 50% split is looking for a `<div>` that only exists when you're logged in (quickedit div). This is probably going to require changes on the d8 side to get it to work correctly.

**Comment by nstriedinger** [comment]
IE 11 -- Am I missing something?

screen shot 2018-12-07 at 1 26 02 pm

**Review by tcfunk — APPROVED** [review]

**Pull request merged**
