### PR TITLE
EWL-5147 - add purple and blue h4

### PR DESCRIPTION
**Pull request by designerneil**
## Ticket(s)

**Jira Ticket**
- [EWL-5147: SG2 | Correct pagination link color and add padding](https://issues.ama-assn.org/browse/EWL-5147)

## Description
Add h4 purple and blue versions

## To Test

- Pull `bugfix/EWL-5147-add-h4-styles` branch
- Run `gulp serve` in ama-style-guide-2/styleguide to ensure a local version of style guide is running.
- visit http://localhost:3000/?p=pages-topic
- observe that the lead news is now purple and has the purple h4 styling
- the purple text should be the following sizes: 
Desktop: Myriad Pro Regular 18/35
Mobile: Myriad Pro Regular 16/23
Tablet: Myriad Pro  Regular 18/28
- use Chrome to inspect the lead news text and change the class to from `ama__h4--purple` to `ama__h4--blue`
- observe the text turns blue with the following sizes:
Desktop:  Myriad Pro Regular 28/35
Mobile: Myriad Pro Regular 18/22
Tablet: Myriad Pro  Regular 18/22

## Visual Regressions
There is no VRT testing for h4 atom elements
N/A

## Relevant Screenshots/GIFs
screen shot 2018-05-23 at 4 21 29 pm

## Remaining Tasks
N/A

## Additional Notes
N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Review by JaeBea — CHANGES_REQUESTED** [review]
@designerneil There are a few changes needed for this to be merged.

1. The text should be all caps for both styles.
2. The desktop font size is incorrect for the purple style.
3. The tablet line-height is incorrect for the purple style.

**Comment by JaeBea** [comment]
@designerneil One additional change: Please update the link text for the JIRA ticket in your description.

**Comment by designerneil** [comment]
@JaeBea thank you for you thorough review

**Review by JaeBea — CHANGES_REQUESTED** [review]
@designerneil  I have confirmed the text sizing and line height changes are correct. There are three more updates needed:
1. Please remove header link changes and add to PR #271. I believe you may have added it to this one by mistake.
2. Lead news organism heading is missing the ama__h4--purple class.
3. Backstop images need updating for all tests containing the lead news organism.

**Pull request merged**
