### PR TITLE
EWL- 5596 category navigation menu

### PR DESCRIPTION
**Pull request by designerneil**
**Jira Ticket**
- [EWL-5596: SG2 | Create "Category Navigation Menu" Organism](https://issues.ama-assn.org/browse/EWL-5596)

## Description
Create a category navigation menu that contains a submenu and article stubs

## To Test
- [x] `gulp serve`
- [x] visit http://localhost:3000/?p=organisms-category-navigation-menu
- [x] hover over the links and observe the lighter shade of purple background behind the current link
- [x] hover over a link with a caret and observe a a gray fly-out menu with a drop shadow and two article stubs to right of it
- [x] resize your browser to tablet size
- [x] reload the page
- [x] click on  the link with the caret
- [x] observe a a gray fly out menu with two article stubs stacked
- [x] resize your browser to mobile size
- [x] reload the page
- [x] observe the menu changes to a stacked view
- [x] click a link with a caret
- [x] observe a white menu open below it with purple links
- [x] observe the caret rotates down
- [ ] Did you test in IE 11?

## Visual Regressions
Add a new backstop test: category navigation menu

All testing is done by Travis
http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/feature/EWL-5596-category-navigation-menu/html_report/index.html

## Relevant Screenshots/GIFs
screen shot 2018-07-30 at 10 57 36 am
screen shot 2018-07-30 at 10 57 20 am
screen shot 2018-07-30 at 10 57 03 am

## Remaining Tasks
N/A

## Additional Notes
N/A
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by labbydev** [comment]
@designerneil there are a few issues here with the JavaScript:
* UX has specifically requested that there be a delay on desktop once users hover over an item so that it doesn't open the next sub-menu until they've landed on the next item for a couple of seconds. The example that they gave is Bass Pro: https://www.useloom.com/share/47ce3b79253c418da2dde9045a66e44f
* There is some issues with the opening and closing on mobile that it continues repeatedly a number of times instead of just firing once: https://www.useloom.com/share/ab9285fede834910a802c1ebffd6cc9b

Also it looks like the dropdown is getting the same height as the articles on tablet, however the Zeplin files specifically shows that it should only be as tall as the content. Compare:
screen shot 2018-07-30 at 1 50 39 pm
screen shot 2018-07-30 at 1 50 34 pm

**Comment by designerneil** [comment]
@labbydev the delay in the javascript is going to be further refined when I have the whole menu in place.

**Comment by designerneil** [comment]
As for the height I will go over this issue in our UX collab today

**Comment by designerneil** [comment]
@labbydev the mobile opening and closing is due to the page being resized and not reloaded.

**Comment by designerneil** [comment]
@labbydev I've added a 500ms delay to the mouseover

**Review by labbydev — APPROVED** [review]

**Pull request merged**
