### PR TITLE
EWL-7303 social icons not appearing in footer

### PR DESCRIPTION
**Pull request by designerneil**
## Ticket(s)
**Do not** submit a Pull Request without a relevant JIRA ticket or Github issue! If you are creating a new pattern or feature, create an issue describing the need for this feature in Github **first** and then link to it below.

**Jira Ticket**
- [EWL-7303 Social icons not appearing in footer](https://issues.ama-assn.org/browse/EWL-7303)

## Description
Social icons in the global footer are the wrong color. They should be white

## To Test
- [ ] switch to this branch `bugfix/EWL-7303-Social-icons-not-appearing-in-footer`
- [ ] run `gulp serve`
- [ ] scroll down to the footer and observe the footer icons are now white
- [ ] enable local SG2 in your D8 instance using local.yml
- [ ] run `scripts/build`
- [ ] clear your D8 cache
- [ ] visit the homepage or any page and scroll down to the footer
- [ ] observe the icons are now white
- [ ] Did you test in IE 11?

## Visual Regressions

http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/bugfix/EWL-7303-Social-icons-not-appearing-in-footer/html_report/index.html

## Relevant Screenshots/GIFs
Screen Shot 2019-06-05 at 11 43 09 AM

## Remaining Tasks
Things relevant to here may be updating [The Glossary](https://issues.ama-assn.org:8446/confluence/display/DTD/Glossary?src=contextnavpagetreemode) with the latest naming changes or review of the relative [D8](https://github.com/AmericanMedicalAssociation/ama-d8) work.n/a

## Additional Notes
n/a
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by designerneil** [comment]
@Brian-Clement you'll notice some of the files are about the same but the file structure is different. This is due to the fact I ran a `gulp image` which compresses svgs and images

**Review by Brian-Clement — COMMENTED** [review]
@designerneil I'm seeing something weird with the Footer As Universal:

image

http://localhost:3000/?p=organisms-footer-as-universal

I can't find where this is being used on the AMA One site, so I'm not sure how big an issue it is.  Do you know if/where this gets used on site?

**Comment by designerneil** [comment]
> @designerneil I'm seeing something weird with the Footer As Universal:
> 
> image
> 
> http://localhost:3000/?p=organisms-footer-as-universal
> 
> I can't find where this is being used on the AMA One site, so I'm not sure how big an issue it is. Do you know if/where this gets used on site?

Screen Shot 2019-06-05 at 1 21 06 PM

**Review by Brian-Clement — APPROVED** [review]
@designerneil this looks good.  I'll wait to see if Travis passes, it looks like it has been passing in other branches.

**Pull request merged**
