### PR TITLE
EWL-6801: A1 | Put Workflow Form in a Standard Position

### PR DESCRIPTION
**Pull request by russom-woldezghi**
## Ticket(s)
- [EWL-6801: A1 | Put Workflow Form in a Standard Position](https://issues.ama-assn.org/browse/EWL-6801)

## Description
- Adds grid and margin styling for content moderation workflow form
- Positions content workflow form above h1 title. 
- Depends on this PR on `amd-d8` repo: AmericanMedicalAssociation/ama-d8#1267

## To Test
- Enable sg-development on `local.yml` file (in `ama-d8` repo).
- Pull down code. 
- Pull down the branch for this corresponding pr: https://github.com/AmericanMedicalAssociation/ama-d8/pull/1267
- Edit any of the following node types to view the content moderation workflow form:
   - Banner:
 (no prod->local copy, add a banner here:  http://ama-one.local/node/add/banner, and content workflow form should be visible after saving)
   - Best Bet :
http://ama-one.local/node/24831/latest
 http://ama-one.local/node/24831
   - News Article :
http://ama-one.local/node/27916/latest
 http://ama-one.local/delivering-care/hypertension/how-office-blood-pressure-reading-accuracy-can-still-improve  
   - Press Release: 
http://ama-one.local/node/766/latest 
http://ama-one.local/press-center/press-releases/ama-adopts-guidance-reduce-harm-high-intensity-street-lights
   - Resource Page:
 http://ama-one.local/node/21751/latest 
http://ama-one.local/education/accelerating-change-medical-education/join-medical-school-conversation

Observe that content moderation workflow form is consistent across the listed content types.

## Visual Regressions

A report is available [here](http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/597/html_report/index.html).

### Themed pages
screen shot 2019-03-05 at 10 16 17 am
screen shot 2019-03-05 at 10 16 43 am

### No theme/template pages
screen shot 2019-03-05 at 11 32 10 am

## Remaining Tasks
N/A

## Additional Notes

Some of the content listed in PR: https://github.com/AmericanMedicalAssociation/ama-d8/pull/1267 are not styled and only ensures content workflow form is standardize in position.

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Review by JaeBea — COMMENTED** [review]
Depending on dependent PR this may become un-needed. Will mark as question until then.

**Comment by russom-woldezghi** [comment]
@JaeBea Thanks for that feedback. I have updated the grid-row for the _masthead elements, to rank content moderation first. This should keep all the node types consistent.

**Comment by mrspete** [comment]
@russom-woldezghi beatrice left a question on the d8 side of this; I'm marking them both questions.  https://github.com/AmericanMedicalAssociation/ama-d8/pull/1267

**Comment by russom-woldezghi** [comment]
Closing this PR as this is not need per Beatrice comment here: https://github.com/AmericanMedicalAssociation/ama-d8/pull/1267#issuecomment-476313574

**Pull request closed without merging**
