### PR TITLE
EWL-6881 BP Calculator 

### PR DESCRIPTION
**Pull request by designerneil**
## Ticket(s)

**Jira Ticket**
- [EWL-EWL-6881: BP calculator block](https://issues.ama-assn.org/browse/EWL-6881)

## Description
Create a BP Calculator page. It should contain a masthead, header, calculator and footer 
The calculator should initially only show two rows of inputs for systolic and diastolic entries.
When a user click on the calculate button validation should pick up that the inputs are empty and prompt the user that the first systolic and diastolic inputs are required. If a user enters numbers outside of the range of BP pressure they also be prompted what are good ranges.

## To Test
- [ ] run `gulp serve`
- [ ] click on the navigation > pages > bp calculator
- [ ] observe a page shows with a bp calculator
- [ ] click on calculate
- [ ] observe a validation error occurs under the inputs "Not a valid number"
- [ ] enter a number higher than 299 for systolic input 
- [ ] observe an error shows stating the number needs to less than 299
- [ ] enter 60 in the systolic input and observe an error stating the number needs to be higher than 60
- [ ] enter a number higher than 199 for diastolic input 
- [ ] observe an error shows stating the number needs to less than 199
- [ ] enter 40 in the diastolic input and observe an error stating the number needs to be higher than 40
- [ ] follow the same steps for the first diastolic input
- [ ] click calculate
- [ ] observe a new row shows with purple inputs with the the rounded average of the two row of numbers (round up at 0.5, down if .49)
- [ ] click "+ Add BP Reading" link
- [ ] observe another row shows with a systolic and diastolic input
- [ ] fill in the new inputs
- [ ] click calculate 
- [ ] observe a new average is computed in the purple inputs
- [ ] Did you test in IE 11?

## Relevant Screenshots/GIFs
screen shot 2019-01-24 at 10 32 08 am

## Remaining Tasks
Things relevant to here may be updating [The Glossary](https://issues.ama-assn.org:8446/confluence/display/DTD/Glossary?src=contextnavpagetreemode) with the latest naming changes or review of the relative [D8](https://github.com/AmericanMedicalAssociation/ama-d8) work.

## Additional Notes
Anything more to add? Good things to call out here are:
- are there any PRs in this or other repositories that relate to or affect this PR?
- are there any caveats or oddities testers should know about when testing this PR?
- are there any problems you ran into during your work that you'd like to call out?

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Review by JaeBea — CHANGES_REQUESTED** [review]
@designerneil ,
The javascript works fine, however there are a few changes needed to the styling.
1. The mockups have all rounded corners, current version does not.
2. The mobile version is missing the dashes between inputs and the buttons are not stacked.

image

**Review by JaeBea — CHANGES_REQUESTED** [review]
@designerneil ,
Based on our conversation, the stakeholder was okay as is with the current styles. So please disregard that feedback.

The only change I request is that the output be put in a div instead of a read only input. Once that is updated I will approve and merge into develop.

**Comment by designerneil** [comment]
@JaeBea thanks for your INPUT. The OUTPUTS have been changed to DIVs

**Review by JaeBea — APPROVED** [review]
@designerneil ,
This looks good to go now. I will approve and merge in.

**Pull request merged**
