### PR TITLE
EWL-4879 hub pages

### PR DESCRIPTION
**Pull request by designerneil**
## Ticket(s)

**Jira Ticket**
- [EWL-4879: SG2 | Migrate Hub pages](https://issues.ama-assn.org/browse/EWL-4879)

## Description
Migrate hub page from SG1 to SG2. This includes all variations of the hub headers, hub cards and hub heroes

## To Test
- [ ]  `gulp test`
- [ ] visit http://localhost:3000/?p=pages-hub
- [ ] Observe that hub page with the various variations of the hub cards and hub heroes
- [ ] Observe that the cards and heroes are responsive
- [ ] visit in another tab https://americanmedicalassociation.github.io/AMA-style-guide/?p=templates-hub-page
- [ ] Compare the two pages
- [ ] Are all the variations of the hub cards and heroes present?

## Visual Regressions

- `backstop test` was run
- Adds hub page backstop test  
- Adds new image refs for the hub page
- Hub card and hub hero image refs were added when the PR was updated from develop

## Relevant Screenshots/GIFs
screen shot 2018-05-07 at 2 36 35 pm

## Remaining Tasks
n/a

## Additional Notes
n/a
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by labbydev** [comment]
@designerneil does this depend on PR #219 ? Right now the hub page is empty. 
screen shot 2018-05-08 at 10 55 11 am

**Comment by designerneil** [comment]
@labbydev this PR was branched off #219. It shouldn't need it to work.

**Comment by labbydev** [comment]
Not sure if merging the other PR helped or not, but this is working for me now.

**Review by labbydev — APPROVED** [review]
Looks good, just needs merge conflicts resolved.

**Comment by labbydev** [comment]
@designerneil have you reviewed this with the UX team? If not, that would probably be a good use of the time this afternoon.

**Review by labbydev — APPROVED** [review]

**Pull request merged**
