### PR TITLE
EWL-5303 subcategory exploration organism & EWL-5304 Create "Visual Subcategory" molecule

### PR DESCRIPTION
**Pull request by designerneil**
## Ticket(s)

**Jira Ticket**
- [EWL-5303: SG2 | Create "Subcategory Exploration as with Images" Organism](https://issues.ama-assn.org/browse/EWL-5303)
- [EWL-5304: SG2 | Create "Visual Subcategory" molecule](https://issues.ama-assn.org/browse/EWL-5304)

## Description
Create a new molecule and organism to showcase the subcategory related subcategories.

## To Test
- [x] `gulp serve`
- [x] visit http://localhost:3000/?p=molecules-visual-subcategory
- [x] observe a placeholder image with purple text below it
- [x] observe the whole block is clickable
- [x] visit http://localhost:3000/?p=organisms-subcategory-exploration-as-with-images
- [x] observe a grey background with black text followed by a row of 5 images with purple text underneath
- [x] observe a blue view all link in the bottom right corner
- [x] click on the the View All  link
- [x] observe another row appear below the first
- [x] observe the row has 5 images with purple text underneath
- [x] observe the view all link has now has been replaced with View Less
- [x] resize your browser to tablet size
- [x] observe there are only 3 tiles on the page as opposed to 5
- [x] click view all
- [x] observe another row appear with 5 more tiles in 3 columns
- [x] resize your browser to phone size
- [x] observe there are only 3 tiles on the page
- [x] observe the title takes up 100% of the screen and has it's own row
- [x] click view all
- [x] observe another row appear with 5 more tiles in 3 columns
- [x] Did you test in IE 11? Yes

## Visual Regressions
This PR adds backstop tests for Visual Subcategory and Subcategory Exploration as with Images

**Of note:** 
I had to add back in 2 variants of the the h4 typography: ama__h4--purple and ama__h4--blue. These were removed during a merge. 

By adding these two classes back into the typography.scss the news page header changed from black to purple. The classes were removed from the SCSS file but not in the HTML which resulted in this change.

## Relevant Screenshots/GIFs
screen shot 2018-06-15 at 11 35 20 am
screen shot 2018-06-15 at 11 35 04 am
screen shot 2018-06-15 at 11 34 43 am
screen shot 2018-06-15 at 11 34 37 am
screen shot 2018-06-15 at 11 37 13 am

## Remaining Tasks
N/A

## Additional Notes
During our UX collaboration we have decided that the left and right on mobile is inconsistent with the rest of the design. UX has agreed leaving the Article Stubs stacked is the way to go.

UX has also agreed that on smaller mobile screens there should only be two article stubs as opposed to three as shown in the mockups
 
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by labbydev** [comment]
@designerneil this looks fairly broken when users do not have their browser acting as your expecting. For example I'm on desktop but don't have my browser window full width so I see 4&1 instead of 5 in a single row. 

Can you confirm with UX that the behavior should change on refresh instead of just window resize? Can you confirm that this is acting as it should since it loaded like this and this is not the result of me resizing my browser without reloading. 

screen shot 2018-06-19 at 5 22 32 pm

**Comment by designerneil** [comment]
@labbydev I've cleaned up the javascript to show the proper number of tiles based on viewport size.

**Review by JaeBea — CHANGES_REQUESTED** [review]
Hi @designerneil,
There are a few changes needed before this PR can be approved.

1. There is leftover debug code in your subcategory.js file that is outputting a boolean value to the console. Please remove.

2. Currently all of the molecules are stoping at the end of the subcategory title element. The Zeplin mockups and JIRA ticket require subcategory molecules to wrap around flush to both left and right container bounds. Please review either reference and update accordingly.

3. We have previously agreed to standardize our grid system using css grids. Please update your styles for the organism to use `display: grid` system with `fr` units to maintain our standard (Note: using fr units prevents issues with extra margins).

4. I am getting a backstop error on the `visual subcategory exploration with images`  mobile test. Please rerun and update image.
image

**Comment by designerneil** [comment]
@JaeBea css grids should be used on templates levels and flex on smaller organisms and molecules.

**Review by labbydev — APPROVED** [review]

**Review by labbydev — CHANGES_REQUESTED** [review]
I'm getting some backstop failures, it looks like the reference images need to be updated:
_users_laurenbyrwa_sites_ama-style-guide-2_styleguide_backstop_data_html_report_index html

**Comment by designerneil** [comment]
@JaeBea @labbydev Toph from the UX team has approved the look and feel of this organism. He has agreed the amount of tiles that show up should depend on the size of the viewport as oppose to having a fixed amount of tiles.

**Review by labbydev — APPROVED** [review]

**Pull request merged**
