### PR TITLE
EWL-5814 Themes global search

### PR DESCRIPTION
**Pull request by designerneil**
## Ticket(s)

**Jira Ticket**
- [EWL-5814: A1 | Theme Global Header Search Module](https://issues.ama-assn.org/browse/EWL-5814)

## Description:
Themes global search. This PR also fixes the category-menu.js because that was causing numerous js errors on page which in turn affected search.

## To Test
- [ ] ` gulp serve`
- [ ]  visit http://localhost:3000/?p=organisms-main-navigation
- [ ]   observe the global search looks identical to https://americanmedicalassociation.github.io/ama-style-guide-2/?p=organisms-main-navigation
- [ ]  does the search 
- [ ] Did you test in IE 11?

## Visual Regressions
A report is available [here](http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/feature/EWL-5814-theme-global-search/html_report/index.html).

## Relevant Screenshots/GIFs
screen shot 2018-10-08 at 11 05 28 am

## Remaining Tasks
n/a

## Additional Notes
n/a
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by damontgomery** [comment]
I left feedback in https://github.com/AmericanMedicalAssociation/ama-d8/pull/862. I'm not sure how much is needed here or there.

**Review by damontgomery — DISMISSED** [review]
I left comments in https://github.com/AmericanMedicalAssociation/ama-d8/pull/862. I'm not sure which part is the issue.

**Comment by JaeBea** [comment]
@designerneil ,
There is no comment addressing if the concerns in @damontgomery raised in related PR would be addressed here. Also please clarify your testing instructions for this. Switching this back to `question` status.

**Comment by designerneil** [comment]
@JaeBea I've addressed all of @damontgomery concerns in PR https://github.com/AmericanMedicalAssociation/ama-d8/pull/862

Switching this PR back to `ready for review`

**Comment by Brian-Clement** [comment]
@designerneil can you look into the Travis failure here?

**Comment by nstriedinger** [comment]
Is the search supposed to expand in mobile?

Local
screen shot 2018-10-18 at 2 18 57 pm

americanmedicalassociation.github.io
screen shot 2018-10-18 at 2 20 42 pm

**Comment by designerneil** [comment]
@nstriedinger I get this 
screen shot 2018-10-18 at 2 13 46 pm

**Comment by nstriedinger** [comment]
@designerneil yeah, it looks different than https://americanmedicalassociation.github.io

screen shot 2018-10-18 at 3 19 44 pm

**Comment by designerneil** [comment]
@nstriedinger i assume your speaking of the search icon?

**Comment by nstriedinger** [comment]
@designerneil yes, of course.

**Comment by designerneil** [comment]
@nstriedinger  search icon fixed.

**Comment by nstriedinger** [comment]
@designerneil at 728px view port I see this:

screen shot 2018-10-18 at 5 12 50 pm

**Pull request merged**
