### PR TITLE
EWL-8332: Styling for clear search element on taxonomy pages.

### PR DESCRIPTION
**Pull request by alexmartinez92**
## Ticket(s)
**Do not** submit a Pull Request without a relevant JIRA ticket or Github issue! If you are creating a new pattern or feature, create an issue describing the need for this feature in Github **first** and then link to it below.

**Github Issue**
- [Issue XXX: Issue Title](https://github.com/AmericanMedicalAssociation/AMA-style-guide/issues/XXX)

**Jira Ticket**
- [EWL-8332: Add Clear Search functionality to the search field on Cat, Subcat and Index pages](https://issues.ama-assn.org/browse/EWL-8332)

## Description
Adds styling for Clear Search element on Category, Subcategory and Topic term pages.

## To Test
- Checkout ama-d8 PR: [https://github.com/AmericanMedicalAssociation/ama-d8/pull/2346](https://github.com/AmericanMedicalAssociation/ama-d8/pull/2346)
- Link latest styling from this PR
- Navigate to any Category, Subcategory and/or Topic term page
- Confirm styling follows the zeplins below:

Category Page

Desktop https://zpl.io/bejLRKq (annotation #1)

Tablet https://zpl.io/251wWp3 (not annotated #1)

Mobile https://zpl.io/2y0yeWwm (annotation #1)

Subcategory Page

Desktop https://zpl.io/VDEPlr3 (annotation #51)

Tablet https://zpl.io/aROlxDn (annotated #42)

Mobile https://zpl.io/2yn4PPn (annotation #35)

Index Page

Desktop https://zpl.io/brQnBgL (annotation #20)

Tablet https://zpl.io/VKgnRwW (annotation #19)

Mobile https://zpl.io/2GlNKMm (annotation #15)

## Visual Regressions

_Please provide the pull request ID below. This will then reference the automated VRT report after it has been generated._

A report is available [here](http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/[PULL_REQUEST_ID]/html_report/index.html).

**Before proceeding:** Run visual regression tests locally to ensure new work does not introduce new bugs.

_The visual regression tests always compare against the production version of the style guide. Changes and new work will show up as test failures. Please describe your work so that the report can be reviewed by the team._

If you are creating or updating a pattern be sure you have created or updated the [scenario in `backstop.json`](ama-style-guide-2/styleguide/backstop.json).

_After changes in the report are documented and demonstrate your desired changes, please mark the pull request as `ready for review`.

For more information on visual regression testing review the [How do I run tests?](https://issues.ama-assn.org:8446/confluence/pages/viewpage.action?pageId=23298568) document in Confluence.

## Relevant Screenshots/GIFs
Use something like [Skitch](https://evernote.com/skitch/) or [GIPHY Capture](https://giphy.com/apps/giphycapture) to capture images/gifs to demonstrate behaviors.

## Remaining Tasks
Things relevant to here may be updating [The Glossary](https://issues.ama-assn.org:8446/confluence/display/DTD/Glossary?src=contextnavpagetreemode) with the latest naming changes or review of the relative [D8](https://github.com/AmericanMedicalAssociation/ama-d8) work.

## Additional Notes
Anything more to add? Good things to call out here are:
- are there any PRs in this or other repositories that relate to or affect this PR?
- are there any caveats or oddities testers should know about when testing this PR?
- are there any problems you ran into during your work that you'd like to call out?

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Review by joshuathorne — CHANGES_REQUESTED** [review]
Please double check top and bottom margins. Some margins are duplicated by surrounding elements.

**Comment by alexmartinez92** [comment]
@Dr-Zee new commit is in, added various rules to account for spacing above and below across taxonomy types and desktop, tablet and mobile breakpoints.

**Review by joshuathorne — CHANGES_REQUESTED** [review]
Just needs a small change to 21px top and bottom on tablet and mobile.

**Comment by alexmartinez92** [comment]
@Dr-Zee new commits are in, switched styling so spacing of the Clear element across screen sizes is handled by the the element itself and not relying on spacing of the elements around it.

**Review by joshuathorne — APPROVED** [review]

**Pull request merged**
