### PR TITLE
EWL-5322 backstop test update

### PR DESCRIPTION
**Pull request by designerneil**
## Ticket(s)
**Do not** submit a Pull Request without a relevant JIRA ticket or Github issue! If you are creating a new pattern or feature, create an issue describing the need for this feature in Github **first** and then link to it below.

**Jira Ticket**
- [EWL-5322: Spike - Backstop failures](https://issues.ama-assn.org/browse/EWL-5322)

## Description
There should no errors returned from Backstop tests. Tolerances should be set at zero. Like things need to be grouped together.

## To Test
- [ ] pull` feature/EWL-5322-backstop-failures`
- [ ] run backstop test
- [ ] observe the output in your browers
- [ ] observe 0 failures 

## Visual Regressions
refactors backstop to use the new view all link set within molecules and organisms

## Relevant Screenshots/GIFs
N/A

## Remaining Tasks
N/A

## Additional Notes
Bear in mind this PR wipes out previous backstop reference images. All the images in this PR will be the new starting point for all backstop test references. 

This PR also changes the backstop engine to `puppeteer`. I found the engine to be a bit faster and more reliable than Chromy.

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Review by JaeBea — CHANGES_REQUESTED** [review]
@designerneil There are a few changes that are needed before this can merge.

1. The atoms view all test does not capture all atoms.
image

2. The "agenda" test should look at the overall document not  classes .ama_h2 and .ama_tabs.

3. Image refs for resource and hub page tests needs updating as the video info is no longer overlaying the videos.
image

4. The "search header" test is failing for me.
image

**Comment by JaeBea** [comment]
I believe I have found one of our issues which was with the input font. It was using system fonts. This has been updated and added to this PR.

**Comment by csj1012** [comment]
@designerneil @JaeBea this worked! Only 20 failures which were Google Maps and the video atom (maybe related to the fonts issue Beatrice mentioned, not sure?): 

screen shot 2018-06-12 at 4 39 48 pm
screen shot 2018-06-12 at 4 39 52 pm


In any case these seem like one-off failures so I'm approving, and will leave the rest to you guys. Thanks for the awesome work :) 

*Edit* or maybe we need to set the tolerances higher for those scenarios?

**Review by csj1012 — APPROVED** [review]

**Comment by JaeBea** [comment]
@chelsiejohnston @designerneil One possible solution might be using Google's static map api instead.
https://developers.google.com/maps/documentation/maps-static/intro

**Review by JaeBea — APPROVED** [review]
I am no longer getting backstop failures. However since I contributed to this I can no longer merge.

**Comment by labbydev** [comment]
I am getting an error when running backstop 
```
 ~/Sites/ama-style-guide-2/styleguide  ➦ b587a78c  backstop test
BackstopJS v3.0.39
Loading config:  /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/backstop.json

COMMAND | Executing core for `test`
createBitmaps | Selected 94 of 94 scenarios.

Running CasperJS with:  [ '/usr/local/lib/node_modules/backstopjs/capture/genBitmaps.js',
  '--captureConfigFileName=/var/folders/1z/yvtsghbn517_sjjxvp461r500000gn/T/capture/5f85a56ab982ba510310938897dbe7d010143abc.json' ]
CasperJS:  SyntaxError: Unexpected token '>'
CasperJS:    /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/platform/onBefore.js:2 in loadModule
CasperJS:   /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/platform/bootstrap.js:282 in _compile
CasperJS:   /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/platform/bootstrap.js:126 in .js
CasperJS:   /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/platform/bootstrap.js:278 in _load
CasperJS:   /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/platform/bootstrap.js:311 in require
CasperJS:   /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/platform/bootstrap.js:263 in require
CasperJS:    /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/code/bootstrap.js:302 in patchedRequire
CasperJS:    /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/code/genBitmaps.js:130
CasperJS:    /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/platform/casper.js:1685 in runStep
CasperJS:    /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/platform/casper.js:414 in checkStep
CasperJS:  TypeError: Object is not a constructor (evaluating 'require(getScriptPath(onBeforeScript))(casper, scenario, vp, isReference)')

CasperJS:    /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/code/genBitmaps.js:130
CasperJS:    /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/platform/casper.js:1685 in runStep
CasperJS:    /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/platform/casper.js:414 in checkStep

Testing script failed with code: 1

An unexpected error occurred. You may want to try setting the debug option to `true` in your config file.
      COMMAND | Command `test` ended with an error after [5.406s]
      COMMAND | Error: An unexpected error occurred. You may want to try setting the debug option to `true` in your config file.
                    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/backstopjs/core/util/createBitmaps.js:188:18)
                    at ChildProcess.emit (events.js:180:13)
                    at maybeClose (internal/child_process.js:936:16)
                    at Socket.stream.socket.on (internal/child_process.js:353:11)
                    at Socket.emit (events.js:180:13)
                    at Pipe._handle.close [as _onclose] (net.js:541:12)

```
This is likely something specific to my environment. I will continue debugging this afternoon. FWIW this is using node `v9.9.0` and npm `6.0.1`

**Comment by JaeBea** [comment]
@labbydev This same issue happened with @chelsiejohnston yesterday when she tried to test this. I believe the solution required uninstalling and reinstalling backstop and related packages. You may get another error afterwards about your environment changing, the code to run to resolve it will show with the error.

When entering `which backstop` you should get a path similar to the one below.
/Users/bewillia/.nvm/versions/node/v9.9.0/bin/backstop

If not, run `npm uninstall backstopjs`, then `npm install -g backstopjs`.

**Review by labbydev — APPROVED** [review]

**Pull request merged**
