### PR TITLE
EWL-9223: Update browser-sync and axios packages in styleguide.

### PR DESCRIPTION
**Pull request by alexmartinez92**
## Ticket(s)
**Do not** submit a Pull Request without a relevant JIRA ticket or Github issue! If you are creating a new pattern or feature, create an issue describing the need for this feature in Github **first** and then link to it below.

**Github Issue**
- [N/A

**Jira Ticket**
- [EWL-9233: Styleguide Axios  Upgrade](https://issues.ama-assn.org/browse/EWL-9233)

## Description
Updates browser-sync and axios packages within the styleguide repo.

## To Test
- with latest run 'gulp serve'
- confirm styleguide is accesible
- link-styleguides to local repo
- confirm styles compile when editing and that they are reflected on your local ama-d8 site.

## Visual Regressions
- N/A

## Relevant Screenshots/GIFs
-N/A

## Remaining Tasks
- N/A

## Additional Notes
- N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Review by joshuathorne — COMMENTED** [review]
@alexmartinez92 I'm only seeing an axios update. Where you able to get BrowserSync working?

**Comment by alexmartinez92** [comment]
Yes, it was updated as part of the other branch EWL-9208. That was one of the merge conflicts that was resolved. If you want to verify, confirm the version for browsersync is 2.27.7 and confirm you can open the styleguide locally and still get scss changes to reflect locally via lando link-styleguides command.

**Comment by joshuathorne** [comment]
@alexmartinez92 Okay, so it's updated and compiling is still working properly, but browsersync still isn't really working in browser.

**Comment by joshuathorne** [comment]
@alexmartinez92 Browsersync is I think a fairly complicated fix. I can't view the ticket this PR is addressing, but unless it's specifically about getting browsersync working, don't worry about it.

**Comment by alexmartinez92** [comment]
@joshuathorne after some research, browsersync has not worked on ama-d8 locally since the switch to lando. However, I can verify it does still function on the styleguide itself (patternlab).

**Comment by joshuathorne** [comment]
@alexmartinez92 It actually didn't work in Vagrant either. 
I can't view the ticket this PR is addressing. If it says update Browser sync, then this is good. If it says get browsersync running, the intention is to get it running in Lando. This is not a critical ticket, it's just a nice to have.

**Comment by alexmartinez92** [comment]
@joshuathorne here is the link to the original ticket: [EWL-9233](https://issues.ama-assn.org/browse/EWL-9223). The purpose was to resolve a security issue we were notified of via dependabot on github, specifically for the axios package. The patched version of axios needed required the upgrade of browsersync.

This ticket was not to fix browsersync but to update to the axios to the patched version.

**Comment by joshuathorne** [comment]
@alexmartinez92 Perfect. Thank you, Alex.

**Review by joshuathorne — APPROVED** [review]

**Pull request merged**
