### PR TITLE
Update backstop test

### PR DESCRIPTION
**Pull request by designerneil**
## Ticket(s)

**Jira Ticket**
- [EWL-5342: A1 | Style Guide backstop tests failing](https://issues.ama-assn.org/browse/EWL-5342)

## Description
Third party content is causing backstopjs test to fail sporadically. This PR ignores third party content.
Atoms that were not getting tested are also included in this PR.

## To Test
- [ ] `gulp serve`
- [ ] `backstop test`
- [ ] observe 0 backstop  failures

## Visual Regressions

Adds ignore to third party content in backstop.json
Adds tests for atoms not being tested in view all

## Relevant Screenshots/GIFs
N/A

## Remaining Tasks
N/A

## Additional Notes
N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Review by JaeBea — CHANGES_REQUESTED** [review]
Hi @designerneil,

The ignore selector flags on 3rd party content works as expected, however there are merge conflicts with develop. Once these are resolved I can approve and merge.

**Comment by designerneil** [comment]
@JaeBea conflicts resolved

**Review by labbydev — CHANGES_REQUESTED** [review]
@designerneil I'm getting a regression in the membership promo, please review:
screen shot 2018-06-19 at 5 15 02 pm

**Comment by designerneil** [comment]
@labbydev the only thing changes in this PR is the backstop.json I don't know why you would be getting a regression

**Comment by JaeBea** [comment]
@designerneil I am also getting the exact same error. It is a problem with how the engine rendered the molecule. It left out the title, maybe because of an snag while loading, and then the test image was committed. When ran another time the title is back as it should have been from the beginning. I have seen this happen to me before and I had to rerun backstop before I was able to approve my images.

**Comment by designerneil** [comment]
@JaeBea @labbydev the membership ref image has been restored to it's former glory with title and all. Please rerun your backstop test. Thanks

**Review by JaeBea — APPROVED** [review]
@designerneil Backstop is running without failures. I will merge this in to develop.

**Pull request merged**
