### PR TITLE
EWL-10005 membership block category styling

### PR DESCRIPTION
**Pull request by alexmartinez92**
## Ticket(s)
**Do not** submit a Pull Request without a relevant JIRA ticket or Github issue! If you are creating a new pattern or feature, create an issue describing the need for this feature in Github **first** and then link to it below.

**Github Issue**
- [Issue XXX: Issue Title](https://github.com/AmericanMedicalAssociation/AMA-style-guide/issues/XXX)

**Jira Ticket**
- [EWL-10005: Membership Custom Block | For Category Page | Styleguide component](https://issues.ama-assn.org/browse/EWL-10005)

## Description
Update styling for membership blocks on category pages.

## To Test
- Import latest config 'lando drush @one.local cim -y'
- link styleguide PR: 'lando link-styleguides' 
- navigate to existing top level category page, i.e http://ama-one.lndo.site/about
- edit layout of page, move existing or add new membership block to to a full width column
- save and view page, confirm styling matches the following zeplins:https://app.zeplin.io/project/63bda76d34cc000c4febbb66/screen/63bdaaac6377ad0cac611496

- add/edit existing membership custom block
- confirm 'Media' field appears in form
- add media (image, brightcove or alternative video)
- confirm block can be saved
- add/move block to full width column on top level category page
- confirm block displays and matches the following zeplins:
- https://app.zeplin.io/project/63bda76d34cc000c4febbb66/screen/63cff7283f59617ab25eaa92

- navigate to homepage and subcategories, confirm existing membership blocks have not changed

## Visual Regressions

_Please provide the pull request ID below. This will then reference the automated VRT report after it has been generated._

A report is available [here](http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/[PULL_REQUEST_ID]/html_report/index.html).

**Before proceeding:** Run visual regression tests locally to ensure new work does not introduce new bugs.

_The visual regression tests always compare against the production version of the style guide. Changes and new work will show up as test failures. Please describe your work so that the report can be reviewed by the team._

If you are creating or updating a pattern be sure you have created or updated the [scenario in `backstop.json`](ama-style-guide-2/styleguide/backstop.json).

_After changes in the report are documented and demonstrate your desired changes, please mark the pull request as `ready for review`.

For more information on visual regression testing review the [How do I run tests?](https://issues.ama-assn.org:8446/confluence/pages/viewpage.action?pageId=23298568) document in Confluence.

## Relevant Screenshots/GIFs
Use something like [Skitch](https://evernote.com/skitch/) or [GIPHY Capture](https://giphy.com/apps/giphycapture) to capture images/gifs to demonstrate behaviors.

## Remaining Tasks
Things relevant to here may be updating [The Glossary](https://issues.ama-assn.org:8446/confluence/display/DTD/Glossary?src=contextnavpagetreemode) with the latest naming changes or review of the relative [D8](https://github.com/AmericanMedicalAssociation/ama-d8) work.

## Additional Notes
Anything more to add? Good things to call out here are:
- are there any PRs in this or other repositories that relate to or affect this PR?
- are there any caveats or oddities testers should know about when testing this PR?
- are there any problems you ran into during your work that you'd like to call out?

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Review by joshuathorne — COMMENTED** [review]
This looks great. The only Issues I'm seeing are with the top and bottom padding on tablet and mobile, and also spacing between the text and CTA.

**Review by joshuathorne — DISMISSED** [review]
see comment

**Comment by joshuathorne** [comment]
Also, It looks like the block displays correctly when placed in a One col layout. There is also an AMA One Col layout. If placed there, the block doesn't display with updated styles.

**Comment by alexmartinez92** [comment]
styling is updated, ready for review again.

**Comment by joshuathorne** [comment]
@alexmartinez92 This looks great. I'm only seeing two things.
1. If the block is placed in an AMA One Col layout, the descriptions doesn't display.
2. The max-width of the text field needs to be reduced or rebalanced. If there is a lot of description text, the image is pushed to the right.
Screenshot 2023-03-02 171432

**Comment by alexmartinez92** [comment]
Styling update is in to address the issues, let me know how it looks.

**Review by caharder — APPROVED** [review]

**Pull request merged**
