### PR TITLE
EWL-4601 Fix dropdown sort

### PR DESCRIPTION
**Pull request by designerneil**
Adds checkmark next to currently select option## Ticket(s)

**Jira Ticket**
- [EWL-4601: SG2 | Create Dropdown Sort Atom](https://issues.ama-assn.org/browse/EWL-4601)

## Description
Update select menu to have a checkmark on the selected option

## To Test
- [ ] `gulp serve`
- [ ] visit http://localhost:3000/?p=atoms-select-menu
- [ ] Click on the select menu
- [ ] Select an option
- [ ] Click on the select menu
- [ ] Observe the selected option has a checkmark next to it

## Visual Regressions
ran `backstop test`
Search header backstop test refs updated

## Relevant Screenshots/GIFs
screen shot 2018-05-24 at 3 38 43 pm

## Remaining Tasks
N/A

## Additional Notes
N/A
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Review by JaeBea — CHANGES_REQUESTED** [review]
There are only a couple tweaks needed to have this approved and merged.

1) There should be some padding to the left of the icon.

2) The icon is disappearing when on hover and adds itself to whatever item was last in hover state when leaving the drop down area. While this resolves itself if you click outside the drop down area and begin selection again, the icon should only move when an option is selected.

**Comment by designerneil** [comment]
@JaeBea the icon gets removed because there is a hover state and the user is selecting something else. If the icon were to stay then it would have to change to white to be seen. The transition is a bit strange if that occurs.

In addition jQueryUI removes the active class when hovering. I cannot retain the checkmark if the active class gets removed.

**Comment by designerneil** [comment]
I found if I added padding to the left of the icon the search header was screwed up.

**Comment by designerneil** [comment]
@JaeBea due to the nature of jQueryUI selectmenu the only way I an figure out how make the selects not look weird is to add a checkmark to all options that are being hovered over.

**Comment by JaeBea** [comment]
@designerneil This no longer has the hover purple background. Can you check with UX that this will not be a problem? If they are good with the compromise then I think this is ready to be merged.

**Comment by JaeBea** [comment]
@designerneil Everything looks good, just need updated backstop reference images added and then I will merge.

**Review by labbydev — APPROVED** [review]

**Pull request merged**
