### PR TITLE
EWL-4548: Update masthead to use CSS grid to match indentation of body copy

### PR DESCRIPTION
**Pull request by designerneil**
## Ticket(s)

**Jira Ticket**
- [EWL-4548: SG2 | Masthead on press release page needs to line up with body copy](https://issues.ama-assn.org/browse/EWL-4548)

## Description
Updates masthead organism to match the indentation of the body copy. This was achieved by using the same CSS grid in the two column grid template

## To Test
- [ ] ` gulp serve`
- [ ] visit http://localhost:3000/?p=pages-press-release
- [ ] observe that the masthead is indented and in line with the body copy
- [ ] reduce viewport window to mobile size and observe how the masthead is full width

## Visual Regressions
run `gulp backstop`

## Relevant Screenshots/GIFs
screen shot 2018-02-15 at 3 35 38 pm
screen shot 2018-02-15 at 3 35 31 pm

## Remaining Tasks
N/A

## Additional Notes
N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by designerneil** [comment]
https://github.com/AmericanMedicalAssociation/ama-style-guide-2/pull/111

**Comment by nstriedinger** [comment]
This looks lopsided at Desktop, is that right? Shouldn't it be "centered"?

screen shot 2018-02-22 at 11 34 27 am

I guess we've basically got an empty grid column? That seems wrong.

screen shot 2018-02-22 at 11 34 08 am

**Comment by nstriedinger** [comment]
@designerneil -- pardon, it was confirmed that this layout is correct (I was just making sure). This does have merge conflicts tho.

**Comment by designerneil** [comment]
@nstriedinger the page not being centered is known and UX has approved it.They asked for was for the masthead to match the main content indentation. This PR updates the masthead so it uses the same CSS grid as the main content.

**Pull request merged**
