### PR TITLE
EWL-5011 node security vulnerabilities patch

### PR DESCRIPTION
**Pull request by designerneil**
## Ticket(s)

**Jira Ticket**
- [EWL-5011: SG2 | Update hapijs/hoek](https://issues.ama-assn.org/browse/EWL-5011)

## Description
Update node modules to patch security vulnerabilities

## To Test
- [ ] run `npm update && npm install`
- [ ] `gulp serve`
- [ ] observe if anything is broken in SG2

## Visual Regressions
N/A

## Relevant Screenshots/GIFs
N/A

## Remaining Tasks
N/A

## Additional Notes
N/A
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by labbydev** [comment]
@designerneil when I run `npm update && npm install` I get changes to `styleguide/package-lock.json` I also get:
```
[!] 54 vulnerabilities found [19651 packages audited]

    Severity: 39 low | 11 moderate | 4 high
    Run `npm audit` for more detail
```

It's worth mentioning that I'm running `node v9.9.0` and `npm 6.0.0`

**Review by labbydev — COMMENTED** [review]
@designerneil when I run `npm update && npm install` I get changes to `styleguide/package-lock.json` I also get:
```
[!] 54 vulnerabilities found [19651 packages audited]

    Severity: 39 low | 11 moderate | 4 high
    Run `npm audit` for more detail
```

It's worth mentioning that I'm running `node v9.9.0` and `npm 6.0.0`

**Comment by designerneil** [comment]
@labbydev the 4 high security vulnerabilities cannot be fixed it's from minimatch. It's a known issue from Gulp 3.9.1 and Gulp SASS 3.2.1 which uses minimatch and needs to update their dependency to at least version 3.0.2. 
https://test.snyk.io/node-js/gulp-sass
https://snyk.io/test/npm/gulp-sass/0.7.3?severity=high&severity=medium&severity=low

Gulp will need to be updated to at least 4.0.0 to resolve this security error.

We are using minimatch 3.0.4 in our package.json.

**Comment by designerneil** [comment]
I have upgraded all of our packages to the latest and greatest to plug any security holes. All of the remaining moderate to low security warnings are from dependencies stemming from installed packages.

**Comment by designerneil** [comment]
The audit you are seeing was installed by me to show security holes with our packages.

**Pull request merged**
