### PR TITLE
EWL-6479 related block search

### PR DESCRIPTION
**Pull request by designerneil**
**Jira Ticket**
- [EWL-6479: Related block to bottom of search page](https://issues.ama-assn.org/browse/EWL-6479)

## Description
Adds styling to promo as inline block for search results. The styling comes from a Zeplin mockup:

zeplin

## To Test
- [ ]  `gulp serve`
- [ ] the rest of the testing procedure is in a D8 PR 
https://github.com/AmericanMedicalAssociation/ama-d8/pull/1039
- [ ] Did you test in IE 11?

## Visual Regressions
A report is available [here](http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/bugfix/EWL-6479-related-block-search/html_report/index.html).

## Relevant Screenshots/GIFs
screen shot 2018-11-02 at 2 33 15 pm

## Remaining Tasks
n/a

## Additional Notes
This has a D8 depedency
https://github.com/AmericanMedicalAssociation/ama-d8/pull/1001

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by damontgomery** [comment]
Was unable to review the styling part because the block was not showing up. See https://github.com/AmericanMedicalAssociation/ama-d8/pull/1001.

**Comment by mrspete** [comment]
removing prioirity button after talking to robert

**Review by damontgomery — COMMENTED** [review]
Overall this looks good, but I'm seeing two lines on the bottom and the design shows one between the last search result and the promo.

two-lines

**Comment by designerneil** [comment]
@damontgomery thanks for point that out. the line has been removed.

**Review by damontgomery — COMMENTED** [review]
The second line is gone. Is the top gap too large compared to the design?

top_gap

**Comment by designerneil** [comment]
@damontgomery I left the gap so users wouldn't think it's part of the search results. I think you're right about the gap being too large after looking the Zeplin mockup.

screen shot 2018-11-13 at 9 42 53 am

**Comment by designerneil** [comment]
@damontgomery removed padding top

**Review by damontgomery — APPROVED** [review]
This works as described.

Thanks for the updates.

Tested against the Drupal 8 site locally by searching for `test`.

**Comment by mrspete** [comment]
this is deprioritized for launch

**Pull request merged**
