### PR TITLE
EWL-4278: Update NPM packages using Node v9.9.0

### PR DESCRIPTION
**Pull request by designerneil**
## Ticket(s)

**Jira Ticket**
- [EWL-4278:Upgrade Node 7 -> 9](https://issues.ama-assn.org/browse/EWL-4278)

## Description
Updates Node to latest version

## To Test
- [ ] In your terminal write `node -v`
- [ ] if it returns any version lower than v9.9.0 then proceed
- [ ] next write `nvm install  v9.9.0` in your terminal
- [ ] if you don't have nvm installed then go here to find out how http://dev.topheman.com/install-nvm-with-homebrew-to-use-multiple-versions-of-node-and-iojs-easily/
- [ ] then `nvm alias default v9.9.0`
- [ ] `node -v ` should return node v9.9.0
- [ ] `npm install` to install the latest packages

## Visual Regressions

N/A 

## Relevant Screenshots/GIFs
N/A

## Remaining Tasks
N/A

## Additional Notes
N/A
---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Review by Brian-Clement — COMMENTED** [review]
@designerneil, are all the integrity sha changes in package-lock.json expected?  I encountered them locally during a previous node upgrade and resolved them with:

1. Upgrade my local node to whatever the team is using
2. Remove node modules: `rm -rf node_modules/`
3. Clean npm cache: `npm cache clean --force`
4. Revert the changes in your `package-lock.json` file (and this file only).
5. Install dependencies again: `npm i`

Per: https://github.com/npm/npm/issues/16938#issuecomment-339863980

**Comment by JaeBea** [comment]
@designerneil I have gone through testing as described in PR. There is one typo that needs correcting. `nvm alias default vv9.9.0` should be `nvm alias default v9.9.0`.

No errors occurred during the test process. Should we also test specific processes to ensure incompatibilities do not exist?

**Comment by designerneil** [comment]
@JaeBea I guess I have to keep this open until all the FEDS/DEVs go through the upgrade process

**Review by labbydev — COMMENTED** [review]
@designerneil when I run `npm install` after upgrading to `node v9.9.0` I'm still getting changes in the `package-lock.json`

**Comment by designerneil** [comment]
@labbydev I removed my node_modules directory and package.lock. Committed a new package.lock. Hopefully that fixes package.lock getting created on your end.

**Review by chelsiejohnston — APPROVED** [review]
@designerneil this all worked fine for me and I'm now updated successfully

**Pull request merged**
