### PR TITLE
[EWL-5265] SG2 | Create "Subcategory Exploration" Organism

### PR DESCRIPTION
**Pull request by csj1012**
## Ticket(s)

**Jira Ticket**
- [EWL-5265: SG2 | Create "Subcategory Exploration" Organism](https://issues.ama-assn.org/browse/EWL-5265)

## Description
Adds the Subcategory Exploration organism.

## To Test
- [x] `gulp serve`
- [x] Given that I am viewing SG2
- [x] When I click "Organisms" in the menu
- [x] Then I should see "Subcategory Exploration"
- [x] When I click "Subcategory Exploration"
- [x] Then I should see a list of headings (h2)
- [x] And they should be linked to the subcategory pages
- [x] And they should be separated by |
- [x] And I should see a horizontal rule below the list
- [x] Given that I resize the screen to tablet mobile
- [x] Then I should only see a single line of headings
- [x] And I should see "View all subcategories" with an arrow icon
- [x] When I click "View all subcategories"
- [x] Then it should expand to show the full list
- [x] Did you test in IE 11?

## Visual Regressions
Added a test and reference images. This branch was merged in with the new puppeteer stuff from `develop` (prematurely committed there? but still works on this branch), but running `backstop test --filter=subcategory-exploration` should pass 

## Relevant Screenshots/GIFs
Mobile:
> 5265-small

Tablet:
> 5265-medium

Desktop:
> 5265-large

## Remaining Tasks
- [ ] Updating [The Glossary](https://issues.ama-assn.org:8446/confluence/display/DTD/Glossary?src=contextnavpagetreemode) 
- [x] Add backstop reference images

## Additional Notes
N/A

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by labbydev** [comment]
@chelsiejohnston I'm currently unable to run `backstop test` on this branch. I'm getting the following error:
```
~/Sites/ama-style-guide-2/styleguide  ➦ 641a4b43 ●  backstop test
BackstopJS v3.0.39
Loading config:  /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/backstop.json

COMMAND | Executing core for `test`
createBitmaps | Selected 80 of 80 scenarios.

Running CasperJS with:  [ '/usr/local/lib/node_modules/backstopjs/capture/genBitmaps.js',
  '--captureConfigFileName=/var/folders/1z/yvtsghbn517_sjjxvp461r500000gn/T/capture/22bedfd7c08cc95afe997315ec9c13b79e3905b7.json' ]
CasperJS:  Debug is enabled!
CasperJS:  [info] [phantom] Starting...
CasperJS:  [info] [phantom] Running suite: 3200 steps
CasperJS:  [debug] [phantom] Successfully injected Casper client-side utilities
CasperJS:  SyntaxError: Unexpected token '>'
CasperJS:    /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/platform/onBefore.js:2 in loadModule
CasperJS:    /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/platform/bootstrap.js:282 in _compile
CasperJS:    /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/platform/bootstrap.js:126 in .js
CasperJS:    /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/platform/bootstrap.js:278 in _load
CasperJS:    /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/platform/bootstrap.js:311 in require
CasperJS:    /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/platform/bootstrap.js:263 in require
CasperJS:    /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/code/bootstrap.js:302 in patchedRequire
CasperJS:    /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/code/genBitmaps.js:130
CasperJS:    /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/platform/casper.js:1685 in runStep

CasperJS:    /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/platform/casper.js:414 in checkStep
CasperJS:  TypeError: Object is not a constructor (evaluating 'require(getScriptPath(onBeforeScript))(casper, scenario, vp, isReference)')
CasperJS:    /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/code/genBitmaps.js:130
CasperJS:    /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/platform/casper.js:1685 in runStep
CasperJS:    /Users/laurenbyrwa/Sites/ama-style-guide-2/styleguide/phantomjs:/platform/casper.js:414 in checkStep
CasperJS:  [debug] [phantom] Navigation requested: url=about:blank, type=Other, willNavigate=true, isMainFrame=true
CasperJS:  [debug] [phantom] url changed to "about:blank"

Testing script failed with code: 1

An unexpected error occurred. You may want to try setting the debug option to `true` in your config file.
      COMMAND | Command `test` ended with an error after [5.686s]
      COMMAND | Error: An unexpected error occurred. You may want to try setting the debug option to `true` in your config file.
                    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/backstopjs/core/util/createBitmaps.js:188:18)
                    at ChildProcess.emit (events.js:182:13)
                    at maybeClose (internal/child_process.js:961:16)
                    at Socket.stream.socket.on (internal/child_process.js:380:11)
                    at Socket.emit (events.js:182:13)
                    at Pipe._handle.close [as _onclose] (net.js:596:12)
```
This is after a fresh `npm install` and `gulp serve`. I did turn on debug mode also and still getting fairly useless responses. (This particular one is _after_ turning on debug mode). 

Were you able to run `backstop test` locally? Maybe we should jump on and look at it together?

**Comment by labbydev** [comment]
@chelsiejohnston after getting my backstop back up and running I'm now getting 20 fails seemingly unrelated items here. Please double check that on your end and I will as well. The diffs I'm seeing look the same and it's not giving me the scrubber to review so I'm going to take _another_ look, _again_.

**Comment by csj1012** [comment]
@labbydev suggestion to address the backstop failures outside of this PR since they're anomalies/occurring in `develop` as well. Suggestion to add this to Dev Chat agenda for Tues. This PR should be ready for re-review.

**Review by JaeBea — CHANGES_REQUESTED** [review]
Hi @chelsiejohnston,

There are a couple of updates needed for this PR.

1. The updates from UX as described in comments on the original ticket do not show in this PR. When clicking on "view all subcategories" I get a select box with a label to the left of it. You may have pushed up the wrong version of this organism.
image

2. This is missing the recent `develop` branch updates that fix many broken backstop tests. Please merge and resolve conflicts/re-add your test cases and ref images.

**Comment by csj1012** [comment]
@JaeBea which branch did you have checked out? The correct branch should be `feature/EWL-5265-create-subcat-exploration-simple-list`

**Comment by JaeBea** [comment]
@chelsiejohnston I pulled the wrong branch when reviewing this the first time. I have now reviewed with the correct branch and see that the organism works as it should. There is only one update needed before I can approve.

Please merge in `develop` one more time so that there are no backstop errors.

**Comment by csj1012** [comment]
@JaeBea thanks, I've merged in `develop` and am now only seeing the following backstop errors (which do not seem related to this PR):

- article stub as video - video text overlay (5 failures, one for each breakpoint)
- hub hero as fifty fifty video - video text overlay (5 failures, one for each breakpoint)
- info card as location - Google maps overlay (5 failures, one for each breakpoint)
- hub heroes - no noticeable difference (1 failure at small breakpoint)
- resource - video text overlay (5 failures, one for each breakpoint)

We may want to address these separately and/or at the next Dev Chat meeting.

**Review by labbydev — CHANGES_REQUESTED** [review]
@chelsiejohnston I'm not seeing the same backstop errors as you mention not being related to this PR. Instead I'm seeing some regressions in:
* The ribbon
* News as Gated
Please see the attached screenshots. 

screen shot 2018-06-19 at 4 06 58 pm

screen shot 2018-06-19 at 4 07 35 pm


I'm also getting a new error on a couple of the backstop tests: `ENGINE ERROR: Navigation Timeout Exceeded: 60000ms exceeded`, but I'm hoping this is a fluke. 

Let me know what you think of the regressions.

**Comment by csj1012** [comment]
Merging in `develop` causes a backstop failure here and a visual regression in `subcategory-exploration.twig` - looks like some overriding styles were added in this commit https://github.com/AmericanMedicalAssociation/ama-style-guide-2/commit/ddff9edecb625571752c221ec8978a9a7e466009

screen shot 2018-06-21 at 12 09 06 pm

@designerneil @labbydev @JaeBea how do you guys think we should move forward since `develop` has issues? I think it might make sense to get the offending files out of `develop` before I merge that in here to resolve the merge conflict in this branch.

**Comment by labbydev** [comment]
I would like to get PR #294 into `develop` and stabilize `develop` that way before moving forward.

**Comment by labbydev** [comment]
@chelsiejohnston PR #294 has been merged, you should be able to move forward with this by merging in `develop` and resolving the merge conflicts.

**Comment by csj1012** [comment]
@labbydev @designerneil I have just merged in `develop` and am still seeing some visual regressions / backstop failures here that appear to be coming from the Visual Subcategory Exploration/with Images stuff:

screen shot 2018-06-22 at 5 31 23 pm
screen shot 2018-06-22 at 5 31 29 pm

Please let me know how to move forward. The offending styles affecting this pattern are coming in through `/assets/css/03-organisms/_subcategory-exploration-as-with-images.scss`

**Comment by labbydev** [comment]
@designerneil can you please take a look at some of these issues? It looks like there isn't enough specificity between your variant pattern and this the base pattern. Feel free to commit directly to this branch as necessary.

**Comment by designerneil** [comment]
@chelsiejohnston @labbydev 
The organism selector has been renamed to .ama__subcategory-exploration-with-images to avoid conflicts with another organism

**Review by labbydev — APPROVED** [review]

**Pull request merged**
