### PR TITLE
EWL-5608:  footer organism

### PR DESCRIPTION
**Pull request by labbydev**
## Ticket(s)
**Jira Ticket**
- [EWL-5608: Update "Footer" and "Footer as Universal" organisms](https://issues.ama-assn.org/browse/EWL-5608)

## Description
Originally the footer tickets were broken out in a logical manner, however the old footer already existed so instead of creating separate sub-molecules it just made sense to update that with the new information. Therefore it didn't require making the additional sub-patterns.

## To Test
- [x] `gulp serve`
- [x] Click "Organisms" in the menu
- [x] Observe you see "Footer"
- [x] Click "Footer"
- [x] Observer you see "Footer" and "Footer as Universal"
- [x] Click "Footer"
- [x] Observe you see the `$homepagePurple` background
- [x] Observe you see the "Site logo as White"
- [x] Observe you see the mission statement as paragraph text
- [x] Observe you see the social icons
- [x] Observe you see the link "Contact Us"
- [x] Observe you see the text "Download AMA Connect app for iPhone or Android"
- [x] Observe you see the footer links in two columns on the right side
- [x] Observe you see the text "The best in medicine, delivered to your inbox"
- [x] Observe you see the subscribe input
- [x] Observe you see the "Products menu" with a gray top border at the bottom
- [x] Observe you see the bottom is `$purple` with a gray border
- [x] Observe you see the legal links on the left
- [x] Observe you see the copyright on the right
- [x] Resize your screen to tablet
- [x] Observe that the footer links are now in a single column
- [x] Resize your screen to mobile
- [x] Observe that the sections are stacked
- [x] Observe there is a gray line between the text to download the connect app and the footer links
- [x] Observe there is a gray line between the footer links and the subscribe input
- [x] Navigate to the "Footer as universal" variant
- [x] Observe that it _does not_ include the subscribe input
- [x] Observe that the "Products menu" includes the link "AMA Home"
- [x] Observe that it is otherwise the same as the "Footer" organism
- [x] Did you test in IE 11?

## Visual Regressions

A report is available [here](http://htmlpreview.github.io/?https://github.com/AmericanMedicalAssociation/ama-style-guide-2/blob/visual-regression-testing-artifact/feature/EWL-5608-footer-organism/html_report/index.html).

## Relevant Screenshots/GIFs
screen shot 2018-07-30 at 5 52 40 pm

screen shot 2018-07-30 at 7 02 16 pm
localhost_3000_patterns_03-organisms-footer-footer_03-organisms-footer-footer html

## Remaining Tasks
* [x] Styling on the subscribe form. 
* [x] Update Markdown
* [x] Update backstop test

## Additional Notes
@designerneil could you take a look at the subscribe form? I can't understand why the exisiting homepage styling with the same markup isn't coming through on the footer. Any ideas?

---

[Guidelines for Contribution](CONTRIBUTING.md)
[SG2 Standards](ama-style-guide-2/docs/standards.md)

### CODE REVIEW

**Comment by designerneil** [comment]
@labbydev you were just missing the parent container.

```
<div class="ama__subscribe-promo--wide">
          <div class="ama__subscribe-promo__form">
            {% include '@atoms/forms/email-field.twig' with { email : footer.email } %}
            {% include '@atoms/button/button.twig' with { button : footer.subscribeButton } %}
          </div>
        </div>
```

**Comment by designerneil** [comment]
@labbydev you probably know this but the social icons are black and need to be white. According to the Zeplin file they need to be 50px x 50px.

**Comment by designerneil** [comment]
The mission statement is too close to the logo. It looks like there should be 45px margin between the two elements

**Comment by designerneil** [comment]
@labbydev  The following things I noticed are different than the Zeplin mockup:


- you probably know this but the social icons are black and need to be white. According to the Zeplin file they need to be 50px x 50px. 
- the social icons on mobile are spread evenly across the screen on mobile
-  The AMA logo looks centered in the Zeplin file on mobile
- The mission statement is too close to the AMA logo. It looks like there should be 45px margin between the two elements
- Download AMA Connect app font weight should be the same as the contact us
- Terms of Use and the links next to it are too big on desktop. They should be 18px
- Terms of Use and the links next to it are too small on tablet. They should be 18px

The footer is really messed up in IE11
screen shot 2018-07-31 at 1 39 02 pm

**Comment by labbydev** [comment]
I have updated the social link size, added some margin to the logo, and fixed the font sizing issues. I have discussed the rest of the items with UX and they think it looks good without change. The icons may be updated in the future but I'm waiting on UX for updated icons and move forward information on that. I've also fixed the formatting in IE11. The proportions between the left and right side of the footer may not be exact but I did review with Nick and he said he likes it so... `/shrug`.

**Review by designerneil — APPROVED** [review]

**Pull request merged**
